@generated
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_caught_exception",
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "root": {
              "filename": "exception_test.py",
              "line": 20,
              "start": 15,
              "end": 22
            },
            "leaves": [
              {
                "kind": "Test",
                "name": "BaseException.__str__",
                "on_all_flows": true
              }
            ]
          }
        ]
      }
    ],
    "sinks": [],
    "tito": []
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_constructed_exception",
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "root": {
              "filename": "exception_test.py",
              "line": 13,
              "start": 11,
              "end": 18
            },
            "leaves": [
              {
                "kind": "Test",
                "name": "BaseException.__str__",
                "on_all_flows": true
              }
            ]
          }
        ]
      }
    ],
    "sinks": [],
    "tito": []
  }
}
{
  "kind": "model",
  "data": {
    "callable": "exception_test.test_parameter_flow",
    "sources": [
      {
        "port": "result",
        "taint": [
          {
            "root": {
              "filename": "exception_test.py",
              "line": 8,
              "start": 11,
              "end": 18
            },
            "leaves": [
              {
                "kind": "Test",
                "name": "BaseException.__str__",
                "on_all_flows": true
              }
            ]
          }
        ]
      }
    ],
    "sinks": [],
    "tito": []
  }
}
