def sqlalchemy.engine.base.Engine.execute(self, __object: TaintSink[SQL], *multiparams, object: TaintSink[SQL], statement: TaintSink[SQL], **params): ...
def sqlalchemy.engine.base.Engine.scalar(self, statement: TaintSink[SQL], *multiparams, **params): ...
def sqlalchemy.engine.base.Connection.execute(self, statement: TaintSink[SQL], *multiparams, **params): ...
def sqlalchemy.engine.base.Connection.scalar(self, object_: TaintSink[SQL], *multiparams, **params): ...
def sqlalchemy.engine.interfaces.Connectable.execute(self, object_: TaintSink[SQL], *multiparams, **params): ...
def sqlalchemy.engine.interfaces.Connectable.scalar(self, object_: TaintSink[SQL], *multiparams, **params): ...

# Disabling these models because the model verification code seems to have a bug:
# - the signature changed to use a PEP 612-style Concatenate in the latest typeshed bump.
# - this *shouldn't* have mattered for the Pysa model, but model verification chokes with a nonsense error
#
# def sqlalchemy.engine.base.Connection.run_callable(self, callable_: TaintSink[SQL], *args, **kwargs): ...
# def sqlalchemy.engine.base.Engine.run_callable(self, callable_: TaintSink[SQL], *args, **kwargs): ...
