@generated
{
  "aliases_explicit.py": [
    "Line 69: Expected 1 errors",
    "Line 70: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 23: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 27: Unexpected errors [\"Expected `GoodTypeAlias13` to be a type alias, got Literal['int | str']\"]",
    "Line 28: Unexpected errors [\"untype, got Literal['int | str']\"]",
    "Line 29: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr']",
    "Line 38: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 41: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[GoodTypeAlias9, Error]\"]",
    "Line 53: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 54: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 57: Unexpected errors ['assert_type(Any, Callable[[int, str, str], None]) failed']",
    "Line 60: Unexpected errors ['assert_type(Callable[ParamSpec(ParamSpec[P]), None], Callable[..., None]) failed']",
    "Line 61: Unexpected errors ['assert_type(Any, int | str) failed']",
    "Line 62: Unexpected errors ['assert_type(list[Any], list[int | str]) failed']",
    "Line 63: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr']",
    "Line 97: Unexpected errors ['Expected a callable, got LegacyExplicitTypeAlias[ListAlias, type[list[Error]]]']",
    "Line 98: Unexpected errors ['assert_type(Any, list[str]) failed']"
  ],
  "aliases_implicit.py": [
    "Line 78: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 80: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 112: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 14: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 18: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 38: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 51: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 64: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 65: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 68: Unexpected errors ['assert_type(Any, Callable[[int, str, str], None]) failed']",
    "Line 72: Unexpected errors ['assert_type(Callable[ParamSpec(ParamSpec[P]), None], Callable[..., None]) failed']",
    "Line 89: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED map[@_] <: LiteralString', 'EXPECTED map[@_] <: str', 'Expected 0 positional argument(s)']",
    "Line 92: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 94: Unexpected errors ['TODO: Lambda(ExprLambda - Answers::expr_infer']",
    "Line 95: Unexpected errors ['Expected `list.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[list[type[int]]], SupportsIndex], _PyreReadOnly_[type[int]]] | Callable[[_PyreReadOnly_[list[type[int]]], slice[Error, Error, Error]], list[_PyreReadOnly_[type[int]]]] | Callable[[list[type[int]], SupportsIndex], type[int]] | Callable[[list[type[int]], slice[Error, Error, Error]], list[type[int]]]']",
    "Line 127: Unexpected errors ['Expected a callable, got type[list]']",
    "Line 128: Unexpected errors ['assert_type(Any, list[str]) failed']",
    "Line 130: Unexpected errors ['Expected a callable, got type[list[int]]']",
    "Line 131: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "aliases_newtype.py": [
    "Line 32: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 13: Unexpected errors ['untype, got NewType', 'Expected a callable, got NewType']",
    "Line 15: Unexpected errors ['assert_type(Any, int) failed', 'Expected a callable, got NewType']",
    "Line 54: Unexpected errors ['untype, got object']"
  ],
  "aliases_recursive.py": [
    "Line 19: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 14: Unexpected errors [\"untype, got Literal['Json']\", \"untype, got Literal['Json']\"]",
    "Line 24: Unexpected errors [\"untype, got Literal['Json2']\", \"untype, got Literal['Json2']\"]",
    "Line 30: Unexpected errors [\"untype, got Literal['RecursiveTuple']\"]",
    "Line 42: Unexpected errors [\"untype, got Literal['RecursiveMapping']\"]",
    "Line 58: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 59: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 62: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 65: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]",
    "Line 68: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]"
  ],
  "aliases_type_statement.py": [
    "Line 26: Expected 1 errors",
    "Line 31: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 9: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 21: Unexpected errors [\"Missing argument 'flush'\", 'Cannot use type alias `GoodAlias1` as a value']",
    "Line 22: Unexpected errors [\"Missing argument 'flush'\", 'Cannot use type alias `GoodAlias1` as a value']",
    "Line 72: Unexpected errors [\"Can't apply arguments to non-class, got @_\"]",
    "Line 77: Unexpected errors [\"Can't apply arguments to non-class, got @_\"]",
    "Line 82: Unexpected errors ['untype, got list[type[int] | type[str]]']",
    "Line 88: Unexpected errors [\"Can't apply arguments to non-class, got @_\"]"
  ],
  "aliases_typealiastype.py": [
    "Line 44: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 17: Unexpected errors ['EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 18: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 19: Unexpected errors [\"Can't apply arguments to non-class, got @_\", 'EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 22: Unexpected errors [\"Can't apply arguments to non-class, got @_\", 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 23: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[TStr]], type[ParamSpec[P]], type[TypeVarTuple[Ts]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 30: Unexpected errors [\"Missing argument 'flush'\", 'EXPECTED Callable[[], Any] <: object']",
    "Line 31: Unexpected errors [\"Missing argument 'flush'\", 'EXPECTED Callable[[], tuple[ParamSpec | TypeVar | TypeVarTuple, ...]] <: object']",
    "Line 35: Unexpected errors ['untype, got GenericAlias']",
    "Line 36: Unexpected errors ['untype, got GenericAlias']",
    "Line 37: Unexpected errors ['untype, got GenericAlias']",
    "Line 38: Unexpected errors ['untype, got GenericAlias']",
    "Line 39: Unexpected errors ['untype, got GenericAlias', 'TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "aliases_variance.py": [
    "Line 24: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "annotations_coroutines.py": [],
  "annotations_forward_refs.py": [
    "Line 22: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 87: Unexpected errors ['untype, got Callable[[ClassD], None]']",
    "Line 96: Unexpected errors ['assert_type(Any, int) failed']"
  ],
  "annotations_generators.py": [
    "Line 51: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 91: Expected 1 errors",
    "Line 46: Unexpected errors ['TODO: ExprYield - Answers::expr_infer']",
    "Line 48: Unexpected errors ['EXPECTED C <: Generator[A, B, C]']",
    "Line 56: Unexpected errors ['EXPECTED None <: Generator[A, B, C]']",
    "Line 63: Unexpected errors ['EXPECTED Literal[3] <: Generator[A, int, Any]']",
    "Line 65: Unexpected errors ['EXPECTED None <: Generator[A, int, Any]']",
    "Line 70: Unexpected errors ['TODO: ExprYield - Answers::expr_infer']",
    "Line 79: Unexpected errors ['EXPECTED None <: Generator[None, None, None]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 83: Unexpected errors ['EXPECTED None <: Iterator[dict[str, int]]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 101: Unexpected errors ['EXPECTED None <: IntIterator', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 110: Unexpected errors ['EXPECTED None <: AsyncIntIterator', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 114: Unexpected errors ['EXPECTED None <: Iterator[A]', 'TODO: YieldFrom(ExprYieldFrom - Answers::expr_infer']",
    "Line 123: Unexpected errors ['EXPECTED None <: Generator[None, float, None]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 127: Unexpected errors ['EXPECTED None <: Generator[None, int, None]', 'TODO: YieldFrom(ExprYieldFrom - Answers::expr_infer']",
    "Line 131: Unexpected errors ['EXPECTED None <: Generator[None, int, None]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 139: Unexpected errors ['EXPECTED None <: Iterable[str]']",
    "Line 140: Unexpected errors ['EXPECTED None <: Iterable[str]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 144: Unexpected errors ['EXPECTED None <: AsyncIterable[str]']",
    "Line 145: Unexpected errors ['EXPECTED None <: AsyncIterable[str]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 149: Unexpected errors ['TODO: YieldFrom(ExprYieldFrom - Answers::expr_infer']",
    "Line 150: Unexpected errors ['EXPECTED None <: Generator[int, None, None]', 'TODO: YieldFrom(ExprYieldFrom - Answers::expr_infer']",
    "Line 154: Unexpected errors [\"Missing argument 'result'\", 'EXPECTED Literal[1] <: float']",
    "Line 159: Unexpected errors ['EXPECTED None <: AsyncGenerator[str, None]', 'Expected `list.__iter__` to be a callable, got Callable[[_PyreReadOnly_[list[int]]], Iterator[_PyreReadOnly_[int]]] | Callable[[list[int]], Iterator[int]]']",
    "Line 160: Unexpected errors [\"Missing argument 'result'\", 'EXPECTED Literal[1] <: float']",
    "Line 161: Unexpected errors ['TODO: ExprYield - Answers::expr_infer']",
    "Line 167: Unexpected errors ['assert_type(Coroutine[Any, Any, AsyncGenerator[str, None]], AsyncGenerator[str, None]) failed']",
    "Line 168: Unexpected errors ['EXPECTED Coroutine[Unknown, Unknown, AsyncGenerator[str, None]] <: AsyncGenerator[str, None]']",
    "Line 174: Unexpected errors ['assert_type(Coroutine[Any, Any, AsyncGenerator[str, None]], AsyncGenerator[str, None]) failed']",
    "Line 175: Unexpected errors ['EXPECTED Coroutine[Unknown, Unknown, AsyncGenerator[str, None]] <: AsyncIterator[str]']",
    "Line 179: Unexpected errors ['EXPECTED None <: AsyncIterator[int]']",
    "Line 187: Unexpected errors ['EXPECTED None <: AsyncIterator[int]', 'TODO: ExprYield - Answers::expr_infer']",
    "Line 190: Unexpected errors ['assert_type(Callable[[], Coroutine[Any, Any, AsyncIterator[int]]], Callable[[], AsyncIterator[int]]) failed']"
  ],
  "annotations_methods.py": [
    "Line 19: Unexpected errors ['Expected a callable, got type[T]']",
    "Line 23: Unexpected errors ['Expected a callable, got type[T]']",
    "Line 30: Unexpected errors ['assert_type(Any, A) failed']",
    "Line 31: Unexpected errors ['assert_type(Any, A) failed', \"Missing argument 'cls'\"]",
    "Line 35: Unexpected errors ['assert_type(Any, B) failed']",
    "Line 36: Unexpected errors ['assert_type(Any, B) failed', \"Missing argument 'cls'\"]",
    "Line 48: Unexpected errors ['assert_type(Any, A) failed', 'EXPECTED type[A] <: type[@_]']",
    "Line 49: Unexpected errors ['assert_type(Any, B) failed', 'EXPECTED type[B] <: type[@_]']",
    "Line 50: Unexpected errors ['assert_type(Any, B) failed', 'EXPECTED type[B] <: type[@_]']",
    "Line 51: Unexpected errors ['assert_type(Any, A) failed', 'EXPECTED type[A] <: type[@_]']"
  ],
  "annotations_typeexpr.py": [
    "Line 95: Expected 1 errors",
    "Line 100: Expected 1 errors",
    "Line 15: Unexpected errors ['Expected `__add__` to be a callable, got Callable[[LiteralString, LiteralString], LiteralString] | Callable[[str, str], str]']",
    "Line 26: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 77: Unexpected errors ['assert_type(tuple[Any], tuple[Any, ...]) failed']"
  ],
  "callables_annotation.py": [
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 91: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 51: Unexpected errors ['assert_type(int, tuple[int, ...]) failed']",
    "Line 52: Unexpected errors ['assert_type(int, dict[str, int]) failed']",
    "Line 89: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 145: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 147: Unexpected errors ['EXPECTED Proto1 <: Callable[..., None]']",
    "Line 148: Unexpected errors ['EXPECTED Callable[..., None] <: Proto1']",
    "Line 149: Unexpected errors ['EXPECTED Proto5[Any] <: Callable[..., None]']",
    "Line 150: Unexpected errors ['EXPECTED Callable[..., None] <: Proto5[Any]']",
    "Line 151: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 153: Unexpected errors ['EXPECTED Proto3 <: Callable[..., None]']",
    "Line 154: Unexpected errors ['EXPECTED Callable[..., None] <: Proto3']",
    "Line 155: Unexpected errors ['EXPECTED Proto3 <: Proto4[Ellipsis]']",
    "Line 156: Unexpected errors ['EXPECTED Proto4[Ellipsis] <: Proto3']",
    "Line 157: Unexpected errors ['EXPECTED Proto7 <: Proto6']",
    "Line 167: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 171: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[Callable[ParamSpec(ParamSpec[P]), str]]]\"]",
    "Line 174: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[Callable[ParamSpec(ParamSpec[P]), str]]]\"]",
    "Line 175: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback2, Error]\"]",
    "Line 181: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 182: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 186: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 188: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[CallbackWithInt, Error]\"]"
  ],
  "callables_kwargs.py": [
    "Line 46: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 13: Unexpected errors ['untype, got object']",
    "Line 23: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TD2]\"]",
    "Line 24: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 31: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TD2]\"]",
    "Line 32: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 34: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TD2]\"]",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 41: Unexpected errors ['assert_type(Unpack[TD1], TD1) failed']",
    "Line 47: Unexpected errors ['EXPECTED Literal[1] <: Unpack[TD2]', \"EXPECTED Literal[''] <: Unpack[TD2]\", \"EXPECTED Literal['5'] <: Unpack[TD2]\"]",
    "Line 49: Unexpected errors [\"Unexpected keyword argument 'v1'\", \"Unexpected keyword argument 'v3'\"]",
    "Line 50: Unexpected errors ['TODO: call_infer: unsupported **kwargs argument to call']",
    "Line 62: Unexpected errors [\"Missing argument 'v3'\", 'TODO: call_infer: unsupported **kwargs argument to call']",
    "Line 99: Unexpected errors ['EXPECTED Callable[[KwArgs[Unpack[TD2]]], None] <: TDProtocol1']",
    "Line 100: Unexpected errors ['EXPECTED Callable[[KwArgs[Unpack[TD2]]], None] <: TDProtocol2']",
    "Line 104: Unexpected errors ['EXPECTED Callable[[KwArgs[Unpack[TD2]]], None] <: TDProtocol6']"
  ],
  "callables_protocol.py": [
    "Line 186: Expected 1 errors",
    "Line 187: Expected 1 errors",
    "Line 34: Unexpected errors ['EXPECTED Callable[[Var[bytes], KwOnly[max_len: int | None]], list[bytes]] <: Proto1']",
    "Line 65: Unexpected errors ['EXPECTED Callable[[Var[bytes], KwArgs[str]], None] <: Proto2']",
    "Line 78: Unexpected errors ['EXPECTED Callable[[Var[bytes], KwArgs[str]], None] <: Proto3']",
    "Line 79: Unexpected errors ['EXPECTED Callable[[Var[bytes]], None] <: Proto3']",
    "Line 80: Unexpected errors ['EXPECTED Callable[[Var[str], KwArgs[str]], None] <: Proto3']",
    "Line 81: Unexpected errors ['EXPECTED Callable[[Var[bytes], KwArgs[bytes]], None] <: Proto3']",
    "Line 82: Unexpected errors ['EXPECTED Callable[[KwArgs[str]], None] <: Proto3']",
    "Line 109: Unexpected errors ['EXPECTED Callable[[int, str], int] <: Proto5']",
    "Line 135: Unexpected errors ['EXPECTED Class7_1 <: Proto7[int, int]']",
    "Line 144: Unexpected errors ['EXPECTED Class7_2 <: Proto7[int, int]']",
    "Line 168: Unexpected errors ['EXPECTED Callable[[Any], Any] <: Proto8']",
    "Line 196: Unexpected errors [\"Missing argument 'flush'\", 'TODO: Answers::expr_infer attribute: `Callable[[int], str]`.other_attribute']",
    "Line 216: Unexpected errors ['EXPECTED Callable[[], None] <: Proto10']",
    "Line 236: Unexpected errors ['EXPECTED Callable[[int, str, None], Any] <: Proto11']",
    "Line 237: Unexpected errors ['EXPECTED Callable[[int, str, None], Any] <: Proto11']",
    "Line 258: Unexpected errors ['EXPECTED Callable[[Var[Any], KwOnly[kwarg0: Any], KwOnly[kwarg1: Any]], None] <: Proto12']",
    "Line 259: Unexpected errors ['EXPECTED Callable[[Var[Any], KwArgs[Any]], None] <: Proto12']",
    "Line 283: Unexpected errors ['EXPECTED Callable[[str], str] <: Proto13_Default']",
    "Line 286: Unexpected errors ['EXPECTED Callable[[str], str] <: Proto13_NoDefault']",
    "Line 287: Unexpected errors ['EXPECTED Callable[[str], str] <: Proto13_NoDefault']",
    "Line 310: Unexpected errors ['EXPECTED Callable[[KwOnly[path: str]], str] <: Proto14_Default']",
    "Line 312: Unexpected errors ['EXPECTED Callable[[KwOnly[path: str]], str] <: Proto14_NoDefault']",
    "Line 313: Unexpected errors ['EXPECTED Callable[[KwOnly[path: str]], str] <: Proto14_NoDefault']"
  ],
  "callables_subtyping.py": [
    "Line 20: Unexpected errors ['EXPECTED Callable[[float], int] <: Callable[[int], float]']",
    "Line 21: Unexpected errors ['EXPECTED Callable[[float], float] <: Callable[[int], float]']",
    "Line 22: Unexpected errors ['EXPECTED Callable[[int], int] <: Callable[[int], float]']",
    "Line 24: Unexpected errors ['EXPECTED Callable[[float], int] <: Callable[[float], float]']",
    "Line 28: Unexpected errors ['EXPECTED Callable[[float], int] <: Callable[[int], int]']",
    "Line 54: Unexpected errors ['EXPECTED Standard2 <: PosOnly2']",
    "Line 57: Unexpected errors ['EXPECTED Standard2 <: KwOnly2']",
    "Line 79: Unexpected errors ['EXPECTED IntArgs3 <: NoArgs3']",
    "Line 80: Unexpected errors ['EXPECTED FloatArgs3 <: NoArgs3']",
    "Line 83: Unexpected errors ['EXPECTED FloatArgs3 <: IntArgs3']",
    "Line 117: Unexpected errors ['EXPECTED IntStrArgs4 <: PosOnly4']",
    "Line 118: Unexpected errors ['EXPECTED StrArgs4 <: PosOnly4']",
    "Line 121: Unexpected errors ['EXPECTED IntStrArgs4 <: StrArgs4']",
    "Line 123: Unexpected errors ['EXPECTED IntStrArgs4 <: IntArgs4']",
    "Line 148: Unexpected errors ['EXPECTED IntKwargs5 <: NoKwargs5']",
    "Line 149: Unexpected errors ['EXPECTED FloatKwargs5 <: NoKwargs5']",
    "Line 152: Unexpected errors ['EXPECTED FloatKwargs5 <: IntKwargs5']",
    "Line 188: Unexpected errors ['EXPECTED IntStrKwargs6 <: KwOnly6']",
    "Line 189: Unexpected errors ['EXPECTED StrKwargs6 <: KwOnly6']",
    "Line 192: Unexpected errors ['EXPECTED IntStrKwargs6 <: StrKwargs6']",
    "Line 194: Unexpected errors ['EXPECTED IntStrKwargs6 <: IntKwargs6']",
    "Line 211: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[Callable[ParamSpec(ParamSpec[P]), None]]]\"]",
    "Line 213: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[Callable[ParamSpec(ParamSpec[P]), None]]]\"]",
    "Line 239: Unexpected errors ['EXPECTED DefaultArg8 <: NoDefaultArg8']",
    "Line 242: Unexpected errors ['EXPECTED DefaultArg8 <: NoX8']",
    "Line 271: Unexpected errors ['EXPECTED Overloaded9 <: IntArg9']",
    "Line 272: Unexpected errors ['EXPECTED Overloaded9 <: StrArg9']",
    "Line 296: Unexpected errors ['EXPECTED IntStrArg10 <: Overloaded10']"
  ],
  "classes_classvar.py": [
    "Line 45: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 61: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[list[int]]`']",
    "Line 78: Unexpected errors ['assert_type(Literal[3.1], float) failed']",
    "Line 98: Unexpected errors ['EXPECTED str | None <: str']",
    "Line 101: Unexpected errors ['Expected 1 more positional argument(s)', 'Object of class `_PyreReadOnly_` has no attribute `__add__`', 'TODO: Answers::expr_infer attribute: `@_`.__add__', 'TODO: Answers::expr_infer attribute: `None`.__add__', \"EXPECTED Literal['hits'] <: _PyreReadOnly_[dict[str, int]]\", \"EXPECTED Literal['hits'] <: dict[str, int]\", 'EXPECTED Literal[0] <: _PyreReadOnly_[str]', 'EXPECTED Literal[0] <: str']"
  ],
  "classes_override.py": [
    "Line 53: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 89: Expected 1 errors",
    "Lines 56, 65: Expected error (tag 'method4')"
  ],
  "constructors_call_init.py": [
    "Line 56: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 20: Unexpected errors ['EXPECTED Literal[1] <: float']",
    "Line 41: Unexpected errors ['Expected 0 positional argument(s)', 'Expected 0 positional argument(s)']",
    "Line 72: Unexpected errors ['assert_type(Any, Class5[list[int]]) failed', 'Expected a callable, got type[Class5]']",
    "Line 73: Unexpected errors ['assert_type(Any, Class5[int]) failed', 'Expected a callable, got type[Class5[int]]']",
    "Line 74: Unexpected errors ['assert_type(Any, Class5[set[str]]) failed', 'Expected a callable, got type[Class5]']",
    "Line 75: Unexpected errors ['assert_type(Any, Class5[float]) failed', 'Expected a callable, got type[Class5]']",
    "Line 91: Unexpected errors ['assert_type(Class6[Any, Any], Class6[int, str]) failed']",
    "Line 99: Unexpected errors ['assert_type(Class7[Any, Any], Class7[str, int]) failed']"
  ],
  "constructors_call_metaclass.py": [
    "Line 51: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 15: Unexpected errors ['EXPECTED None <: NoReturn', 'Expected 0 positional argument(s)']",
    "Line 20: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 23: Unexpected errors ['assert_type(Class1, NoReturn) failed']",
    "Line 33: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 36: Unexpected errors ['assert_type(Class2, Meta2 | int) failed']",
    "Line 43: Unexpected errors ['Expected a callable, got type[super]', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 48: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 52: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 57: Unexpected errors ['Expected a callable, got type[super]', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 62: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 66: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "constructors_call_new.py": [
    "Line 145: Expected 1 errors",
    "Line 16: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 19: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 20: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 23: Unexpected errors ['assert_type(Class1[Any], Class1[int]) failed', 'Expected 0 positional argument(s)']",
    "Line 24: Unexpected errors ['assert_type(Class1[Any], Class1[float]) failed', 'Expected 0 positional argument(s)']",
    "Line 29: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 49: Unexpected errors ['assert_type(Class3, int) failed', \"Missing argument 'x'\"]",
    "Line 64: Unexpected errors ['assert_type(Class4, Class4 | Any) failed', \"Missing argument 'x'\"]",
    "Line 69: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 75: Unexpected errors ['TODO: StmtTry - Bindings::stmt']",
    "Line 89: Unexpected errors ['assert_type(Class6, Class6 | int) failed', \"Missing argument 'x'\"]",
    "Line 98: Unexpected errors ['Expected a callable, got type[super]', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 116: Unexpected errors ['assert_type(Class8[int], Class8[list[int]]) failed']",
    "Line 117: Unexpected errors ['assert_type(Class8[str], Class8[list[str]]) failed']"
  ],
  "constructors_call_type.py": [
    "Line 30: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 25: Unexpected errors ['Expected a callable, got type[super]', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 29: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\"]",
    "Line 35: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 39: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\"]",
    "Line 63: Unexpected errors ['Expected a callable, got type[T]']",
    "Line 71: Unexpected errors ['Expected a callable, got type[T1]']",
    "Line 79: Unexpected errors ['Expected a callable, got type[T2]']",
    "Line 80: Unexpected errors ['Expected a callable, got type[T2]']"
  ],
  "constructors_callable.py": [
    "Line 35: Unexpected errors ['EXPECTED type[Class1] <: Callable[ParamSpec(@_), @_]']",
    "Line 36: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 37: Unexpected errors ['assert_type(Any, Class1) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 48: Unexpected errors ['EXPECTED type[Class2] <: Callable[ParamSpec(@_), @_]']",
    "Line 49: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 50: Unexpected errors ['assert_type(Any, Class2) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 62: Unexpected errors ['EXPECTED type[Class3] <: Callable[ParamSpec(@_), @_]']",
    "Line 63: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 64: Unexpected errors ['assert_type(Any, Class3) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 76: Unexpected errors ['EXPECTED type[Class4] <: Callable[ParamSpec(@_), @_]']",
    "Line 77: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 78: Unexpected errors ['assert_type(Any, int) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 85: Unexpected errors ['EXPECTED None <: NoReturn', 'Expected 0 positional argument(s)']",
    "Line 93: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 96: Unexpected errors ['EXPECTED type[Class5] <: Callable[ParamSpec(@_), @_]']",
    "Line 97: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 99: Unexpected errors ['TODO: StmtTry - Bindings::stmt']",
    "Line 104: Unexpected errors ['TODO: StmtTry - Bindings::stmt']",
    "Line 124: Unexpected errors ['EXPECTED type[Class6] <: Callable[ParamSpec(@_), @_]']",
    "Line 125: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 126: Unexpected errors ['assert_type(Any, Class6Proxy) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 134: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 141: Unexpected errors ['EXPECTED type[Class6Any] <: Callable[ParamSpec(@_), @_]']",
    "Line 142: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 143: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 160: Unexpected errors ['EXPECTED type[Class7] <: Callable[ParamSpec(@_), @_]']",
    "Line 161: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 164: Unexpected errors ['assert_type(Any, Class7[int]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 165: Unexpected errors ['assert_type(Any, Class7[str]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 178: Unexpected errors ['Expected a callable, got type[super]']",
    "Line 181: Unexpected errors ['EXPECTED type[Class8] <: Callable[ParamSpec(@_), @_]']",
    "Line 182: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 183: Unexpected errors ['assert_type(Any, Class8[str]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 192: Unexpected errors ['EXPECTED type[Class9] <: Callable[ParamSpec(@_), @_]']",
    "Line 193: Unexpected errors ['revealed type: Callable[ParamSpec(@_), @_]']",
    "Line 194: Unexpected errors ['assert_type(Any, Class9) failed', 'Answers::expr_infer wrong number of arguments to call']"
  ],
  "constructors_consistency.py": [
    "Line 22: Unexpected errors ['Expected a callable, got type[super]']"
  ],
  "dataclasses_descriptors.py": [
    "Line 35: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 37: Unexpected errors ['assert_type(Desc1, int) failed']",
    "Line 61: Unexpected errors ['assert_type(Desc2[int], list[int]) failed']",
    "Line 62: Unexpected errors ['assert_type(Desc2[str], list[str]) failed']",
    "Line 63: Unexpected errors ['assert_type(Desc2[str], list[str]) failed']",
    "Line 65: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 66: Unexpected errors ['assert_type(Desc2[int], int) failed']",
    "Line 67: Unexpected errors ['assert_type(Desc2[str], str) failed']",
    "Line 68: Unexpected errors ['assert_type(Desc2[str], str) failed']"
  ],
  "dataclasses_final.py": [
    "Line 27: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 37: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 30: Unexpected errors [\"Unexpected keyword argument 'final_no_default'\", \"Unexpected keyword argument 'final_with_default'\"]"
  ],
  "dataclasses_frozen.py": [
    "Line 17: Expected 1 errors",
    "Lines 22, 23: Expected error (tag 'DC2')",
    "Lines 32, 33: Expected error (tag 'DC4')",
    "Line 14: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "dataclasses_hash.py": [
    "Line 23: Unexpected errors ['EXPECTED DC2 <: Hashable', 'Expected 0 positional argument(s)']",
    "Line 40: Unexpected errors ['EXPECTED DC4 <: Hashable', 'Expected 0 positional argument(s)']",
    "Line 48: Unexpected errors ['EXPECTED DC5 <: Hashable', 'Expected 0 positional argument(s)']",
    "Line 59: Unexpected errors ['EXPECTED DC6 <: Hashable', 'Expected 0 positional argument(s)']",
    "Line 70: Unexpected errors ['EXPECTED DC7 <: Hashable', 'Expected 0 positional argument(s)']"
  ],
  "dataclasses_inheritance.py": [
    "Line 60: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 23: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 37: Unexpected errors ['EXPECTED Literal[15] <: float']",
    "Line 40: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "dataclasses_kwonly.py": [
    "Line 17: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 18: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 19: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 20: Unexpected errors ['Expected 0 positional argument(s)', \"Unexpected keyword argument 'b'\"]",
    "Line 28: Unexpected errors [\"Unexpected keyword argument 'default'\"]",
    "Line 32: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 33: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 34: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 35: Unexpected errors ['Expected 0 positional argument(s)', \"Unexpected keyword argument 'b'\"]",
    "Line 47: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 48: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 49: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 50: Unexpected errors ['Expected 0 positional argument(s)', \"Unexpected keyword argument 'b'\"]",
    "Line 61: Unexpected errors ['Expected 0 positional argument(s)', \"Unexpected keyword argument 'b'\"]",
    "Line 62: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\", \"Unexpected keyword argument 'c'\"]"
  ],
  "dataclasses_order.py": [
    "Line 50: Expected 1 errors",
    "Line 19: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 20: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 46: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "dataclasses_postinit.py": [
    "Line 19: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 23: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "dataclasses_slots.py": [
    "Line 25: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Lines 10, 11: Expected error (tag 'DC1')",
    "Line 48: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 56: Unexpected errors ['Class `DC5` has no class attribute `__slots__`']",
    "Line 57: Unexpected errors ['Object of class `DC5` has no attribute `__slots__`', 'Expected 0 positional argument(s)']"
  ],
  "dataclasses_transform_class.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 60: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\", \"Unexpected keyword argument 'other_name'\"]",
    "Line 68: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 74: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 76: Unexpected errors [\"Unexpected keyword argument 'id'\"]",
    "Line 106: Unexpected errors [\"Unexpected keyword argument 'id'\"]",
    "Line 119: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_converter.py": [
    "Line 118: Expected 1 errors",
    "Line 60: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 64: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 68: Unexpected errors ['Expected 0 positional argument(s)', 'EXPECTED Literal[0] <: SupportsIndex | slice[Error, Error, Error]']",
    "Line 102: Unexpected errors ['EXPECTED type[ConverterClass] <: Callable[[@_], @_]']",
    "Line 103: Unexpected errors ['EXPECTED int | str <: int']",
    "Line 104: Unexpected errors ['EXPECTED type[dict] <: Callable[[@_], @_]']",
    "Line 112: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 114: Unexpected errors [\"EXPECTED Literal['f1'] <: int\"]",
    "Line 115: Unexpected errors [\"EXPECTED Literal['f6'] <: ConverterClass\"]",
    "Line 116: Unexpected errors [\"EXPECTED Literal[b'f6'] <: ConverterClass\"]",
    "Line 121: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 132: Unexpected errors ['EXPECTED type[str] <: Callable[[], str] | None']"
  ],
  "dataclasses_transform_field.py": [
    "Line 55: Unexpected errors ['TODO: Lambda(ExprLambda - Answers::expr_infer']",
    "Line 60: Unexpected errors [\"Unexpected keyword argument 'name'\"]",
    "Line 77: Unexpected errors [\"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_func.py": [
    "Line 61: Expected 1 errors",
    "Line 97: Expected 1 errors",
    "Lines 89, 90: Expected error (tag 'Customer3Subclass')",
    "Line 50: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 53: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 67: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 94: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_meta.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 73: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 60: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\", \"Unexpected keyword argument 'other_name'\"]",
    "Line 69: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 75: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 77: Unexpected errors [\"Unexpected keyword argument 'id'\"]",
    "Line 100: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_usage.py": [
    "Lines 58, 61: Expected error (tag 'DC1')",
    "Lines 64, 67: Expected error (tag 'DC2')",
    "Lines 70, 73: Expected error (tag 'DC3')",
    "Line 22: Unexpected errors ['EXPECTED int <: float']",
    "Line 25: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 35: Unexpected errors ['EXPECTED Callable[[], None] <: InventoryItemInitProto']",
    "Line 38: Unexpected errors [\"Missing argument 'flush'\", 'EXPECTED Callable[[], str] <: object']",
    "Line 39: Unexpected errors [\"Missing argument 'flush'\", 'EXPECTED Callable[[_PyreReadOnly_[object]], bool] <: object']",
    "Line 40: Unexpected errors [\"Missing argument 'flush'\", 'EXPECTED Callable[[object], bool] <: object']",
    "Line 41: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__lt__`']",
    "Line 42: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__le__`']",
    "Line 43: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__gt__`']",
    "Line 44: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__ge__`']",
    "Line 66: Unexpected errors [\"Unexpected keyword argument 'default'\"]",
    "Line 72: Unexpected errors ['EXPECTED Literal[0] <: InitVar[int]']",
    "Line 82: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 92: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 102: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 106: Unexpected errors ['assert_type(Callable[[], int], Callable[[str], int]) failed']",
    "Line 123: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 135: Unexpected errors [\"Unexpected keyword argument 'default'\"]",
    "Line 185: Unexpected errors [\"Unexpected keyword argument 'default'\"]",
    "Line 186: Unexpected errors [\"Unexpected keyword argument 'default_factory'\", 'TODO: Lambda(ExprLambda - Answers::expr_infer']",
    "Line 194: Unexpected errors [\"Unexpected keyword argument 'prop_2'\"]",
    "Line 205: Unexpected errors ['EXPECTED DC15 <: DataclassProto']",
    "Line 213: Unexpected errors ['assert_type(DC16[Any], DC16[int]) failed', 'Expected 0 positional argument(s)']",
    "Line 220: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "directives_assert_type.py": [
    "Line 24: Unexpected errors ['assert_type(ForwardReference, Any) failed', \"untype, got Literal['ForwardReference']\"]"
  ],
  "directives_cast.py": [
    "Line 16: Expected 1 errors",
    "Line 10: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED Generator[int, None, None] <: SupportsNext[@_]', 'Expected 0 positional argument(s)', 'EXPECTED type[str] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 11: Unexpected errors ['EXPECTED type[str] <: object', 'Expected `list.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[list[object]], SupportsIndex], _PyreReadOnly_[object]] | Callable[[_PyreReadOnly_[list[object]], slice[Error, Error, Error]], list[_PyreReadOnly_[object]]] | Callable[[list[object], SupportsIndex], object] | Callable[[list[object], slice[Error, Error, Error]], list[object]]']",
    "Line 13: Unexpected errors ['EXPECTED type[int] <: object']"
  ],
  "directives_deprecated.py": [
    "Line 41: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 69: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 31: Unexpected errors ['No attribute `foo` in module `_directives_deprecated_library`']",
    "Line 39: Unexpected errors ['No attribute `Spam` in module `_directives_deprecated_library`']",
    "Line 119: Unexpected errors ['EXPECTED FooConcrete2 <: SupportsFoo2']"
  ],
  "directives_no_type_check.py": [],
  "directives_reveal_type.py": [
    "Line 14: Unexpected errors ['revealed type: int | str']",
    "Line 15: Unexpected errors ['revealed type: list[int]']",
    "Line 16: Unexpected errors ['revealed type: Any']",
    "Line 17: Unexpected errors ['revealed type: ForwardReference']"
  ],
  "directives_type_checking.py": [
    "Line 11: Unexpected errors [\"EXPECTED Literal[''] <: int\"]",
    "Line 16: Unexpected errors ['Inconsistent type annotations for b: list[str], list[int]']",
    "Line 18: Unexpected errors ['assert_type(list[int] | list[str], list[int]) failed']"
  ],
  "directives_type_ignore.py": [],
  "directives_type_ignore_file1.py": [
    "Line 16: Unexpected errors [\"EXPECTED Literal[''] <: int\"]"
  ],
  "directives_type_ignore_file2.py": [],
  "directives_version_platform.py": [],
  "enums_behaviors.py": [
    "Line 39: Expected 1 errors",
    "Line 19: Unexpected errors ['TODO: Answers::solve_binding - Binding::IterableValue']",
    "Line 20: Unexpected errors ['assert_type(Any, Color) failed']",
    "Line 26: Unexpected errors ['assert_type(type[Color], Color) failed', 'Expected 0 type arguments for class `Color`, got 1.', \"untype, got Literal['RED']\"]",
    "Line 27: Unexpected errors ['Expected 0 positional argument(s)']"
  ],
  "enums_definition.py": [
    "Line 75: Unexpected errors ['assert_type(Literal[1], Literal[False]) failed', 'TODO: Attribute(ExprAttribute - Lit::from_expr']"
  ],
  "enums_expansion.py": [
    "Line 23: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 29: Unexpected errors ['TODO: StmtMatch - Bindings::stmt']",
    "Line 50: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 57: Unexpected errors ['TODO: StmtMatch - Bindings::stmt']",
    "Line 78: Unexpected errors ['EXPECTED list[object] <: list[Answer]']"
  ],
  "enums_member_names.py": [],
  "enums_member_values.py": [
    "Line 78: Expected 1 errors",
    "Line 90: Unexpected errors ['Could not find import of `_enums_member_values`, Could not find path for `_enums_member_values`', 'Could not import `ColumnType` from `_enums_member_values`']"
  ],
  "enums_members.py": [
    "Line 50: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 83: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 129: Expected 1 errors",
    "Line 27: Unexpected errors ['assert_type(Literal[Pet.genus], str) failed']",
    "Line 28: Unexpected errors ['assert_type(Literal[Pet.species], str) failed']",
    "Line 33: Unexpected errors ['Could not find import of `_enums_members`, Could not find path for `_enums_members`', 'Could not import `Pet2` from `_enums_members`']",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 36: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 37: Unexpected errors ['assert_type(Any, Literal[False]) failed', 'TODO: Attribute(ExprAttribute - Lit::from_expr']",
    "Line 38: Unexpected errors ['assert_type(Any, Literal[False]) failed', 'TODO: Attribute(ExprAttribute - Lit::from_expr']",
    "Line 67: Unexpected errors ['TODO: Lambda(ExprLambda - Answers::expr_infer', 'Could not find name `x`']",
    "Line 68: Unexpected errors ['EXPECTED Callable[[int], int] <: Callable[ParamSpec(@_), int]']",
    "Line 75: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 100: Unexpected errors ['assert_type(Literal[TrafficLight.AMBER], Literal[TrafficLight.YELLOW]) failed']",
    "Line 128: Unexpected errors ['Could not find name `reveal_type`', 'revealed type: Literal[Example2.__B]']"
  ],
  "exceptions_context_managers.py": [
    "Line 64: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 71: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 78: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 85: Unexpected errors ['assert_type(int | str, str) failed']"
  ],
  "generics_base_class.py": [
    "Line 30: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 45: Unexpected errors ['assert_type(Iterator[Any], Iterator[int]) failed', 'Expected 1 more positional argument(s)', 'EXPECTED LinkedList[int] <: Callable[[], @_]']",
    "Line 46: Unexpected errors ['EXPECTED Literal[1] <: _PyreReadOnly_[object]']",
    "Line 58: Unexpected errors ['assert_type(Any, int) failed', 'Expected `MyDict.__getitem__` to be a callable, got Callable[[Mapping[str, int], str], int] | Callable[[_PyreReadOnly_[Mapping[str, int]], _PyreReadOnly_[str]], _PyreReadOnly_[int]]']"
  ],
  "generics_basic.py": [
    "Line 49: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Line 19: Unexpected errors ['Expected `Sequence.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[Sequence[T]], int], _PyreReadOnly_[T]] | Callable[[_PyreReadOnly_[Sequence[T]], slice[Error, Error, Error]], _PyreReadOnly_[Sequence[T]]] | Callable[[Sequence[T], int], T] | Callable[[Sequence[T], slice[Error, Error, Error]], Sequence[T]]']",
    "Line 34: Unexpected errors ['TODO: Answers::expr_infer attribute: `AnyStr`.__add__']",
    "Line 67: Unexpected errors ['assert_type(MyStr, str) failed']",
    "Line 68: Unexpected errors ['assert_type(MyStr, str) failed', 'EXPECTED str <: MyStr']",
    "Line 92: Unexpected errors ['Expected `__add__` to be a callable, got Callable[[LiteralString, LiteralString], LiteralString] | Callable[[str, str], str]', 'EXPECTED T <: object']",
    "Line 96: Unexpected errors ['Expected `__add__` to be a callable, got Callable[[LiteralString, LiteralString], LiteralString] | Callable[[str, str], str]', 'EXPECTED T <: object']",
    "Line 100: Unexpected errors ['EXPECTED str <: LiteralString', 'EXPECTED str <: LiteralString']",
    "Line 139: Unexpected errors ['assert_type(Any, int) failed', 'Expected 1 more positional argument(s)', 'EXPECTED MyIter1[int] <: SupportsNext[@_]']",
    "Line 140: Unexpected errors ['assert_type(Any, int) failed', 'Expected 1 more positional argument(s)', 'EXPECTED MyIter2[int] <: SupportsNext[@_]']",
    "Line 154: Unexpected errors ['assert_type(Any, int) failed', 'Expected `MyMap1.__getitem__` to be a callable, got Callable[[Mapping[str, int], str], int] | Callable[[_PyreReadOnly_[Mapping[str, int]], _PyreReadOnly_[str]], _PyreReadOnly_[int]]']",
    "Line 155: Unexpected errors ['assert_type(Any, int) failed', 'Expected `MyMap2.__getitem__` to be a callable, got Callable[[Mapping[str, int], str], int] | Callable[[_PyreReadOnly_[Mapping[str, int]], _PyreReadOnly_[str]], _PyreReadOnly_[int]]']",
    "Line 182: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED MyIterableAny <: Callable[[], @_]']"
  ],
  "generics_defaults.py": [
    "Line 24: Expected 1 errors",
    "Line 104: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 30: Unexpected errors ['assert_type(type[NoNonDefaults], type[NoNonDefaults[str, int]]) failed']",
    "Line 31: Unexpected errors ['assert_type(type[NoNonDefaults[Any, Any]], type[NoNonDefaults[str, int]]) failed', 'Expected 2 type arguments for class `NoNonDefaults`, got 1.']",
    "Line 38: Unexpected errors ['assert_type(type[OneDefault[Any, Any]], type[OneDefault[float, bool]]) failed', 'Expected 2 type arguments for class `OneDefault`, got 1.']",
    "Line 39: Unexpected errors ['assert_type(OneDefault[Any, Any], OneDefault[float, bool]) failed', 'Expected 2 type arguments for class `OneDefault`, got 1.']",
    "Line 45: Unexpected errors ['assert_type(type[AllTheDefaults], type[AllTheDefaults[Any, Any, str, int, bool]]) failed']",
    "Line 46: Unexpected errors ['assert_type(type[AllTheDefaults[Any, Any, Any, Any, Any]], type[AllTheDefaults[int, complex, str, int, bool]]) failed']",
    "Line 47: Unexpected errors ['Expected 5 type arguments for class `AllTheDefaults`, got 2.']",
    "Line 52: Unexpected errors ['assert_type(type[AllTheDefaults[Any, Any, Any, Any, Any]], type[AllTheDefaults[int, complex, str, int, bool]]) failed']",
    "Line 53: Unexpected errors ['Expected 5 type arguments for class `AllTheDefaults`, got 2.']",
    "Line 55: Unexpected errors ['assert_type(type[AllTheDefaults[Any, Any, Any, Any, Any]], type[AllTheDefaults[int, complex, str, int, bool]]) failed']",
    "Line 56: Unexpected errors ['Expected 5 type arguments for class `AllTheDefaults`, got 3.']",
    "Line 59: Unexpected errors ['assert_type(type[AllTheDefaults[Any, Any, Any, Any, Any]], type[AllTheDefaults[int, complex, str, int, bool]]) failed']",
    "Line 60: Unexpected errors ['Expected 5 type arguments for class `AllTheDefaults`, got 4.']",
    "Line 76: Unexpected errors ['untype, got ParamSpec']",
    "Line 79: Unexpected errors ['assert_type(type[Class_ParamSpec], type[Class_ParamSpec]) failed', 'Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 80: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 81: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 1.', 'untype, got list[type[bool]]', 'Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 91: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 94: Unexpected errors ['assert_type(type[Class_TypeVarTuple], type[Class_TypeVarTuple]) failed', 'Expected 0 type arguments for class `Class_TypeVarTuple`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 95: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 96: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.', 'Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 127: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 148: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got ParamSpec']",
    "Line 151: Unexpected errors ['Expected 0 type arguments for class `Foo6`, got 2.', 'Expected 0 type arguments for class `Foo6`, got 3.', 'untype, got list[type[bool] | type[float]]']",
    "Line 152: Unexpected errors ['Expected 0 type arguments for class `Foo6`, got 3.', 'untype, got list[type[bytes]]', 'Expected 0 type arguments for class `Foo6`, got 3.', 'untype, got list[type[bytes]]']",
    "Line 166: Unexpected errors ['assert_type(Any, Callable[[Foo7[int]], Foo7[int]]) failed', 'Generic attribute `meth` of class `Foo7` is not visible on the class']",
    "Line 167: Unexpected errors ['assert_type(Any, int) failed', 'Generic attribute `attr` of class `Foo7` is not visible on the class']"
  ],
  "generics_defaults_referential.py": [
    "Line 53: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 74: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 23: Unexpected errors ['assert_type(type[slice], type[slice[int, int, int | None]]) failed']",
    "Line 24: Unexpected errors ['assert_type(slice[Any, Any, Any], slice[int, int, int | None]) failed']",
    "Line 25: Unexpected errors ['assert_type(slice[Any, Any, Any], slice[str, str, int | None]) failed', 'Expected 3 type arguments for class `slice`, got 1.']",
    "Line 94: Unexpected errors ['assert_type(type[Bar], type[Bar[Any, list[Any]]]) failed']",
    "Line 95: Unexpected errors ['assert_type(type[Bar[Any, Any]], type[Bar[int, list[int]]]) failed', 'Expected 2 type arguments for class `Bar`, got 1.']",
    "Line 96: Unexpected errors ['assert_type(Bar[Any, Any], Bar[int, list[int]]) failed', 'Expected 2 type arguments for class `Bar`, got 1.']"
  ],
  "generics_defaults_specialization.py": [
    "Line 30: Expected 1 errors",
    "Line 25: Unexpected errors ['untype, got Forall[DefaultStrT, LegacyExplicitTypeAlias[MyAlias, type[SomethingWithNoDefaults[int, DefaultStrT]]]]']",
    "Line 26: Unexpected errors ['assert_type(Any, SomethingWithNoDefaults[int, str]) failed']",
    "Line 45: Unexpected errors ['assert_type(type[Bar], type[Bar[str]]) failed']",
    "Line 46: Unexpected errors ['assert_type(Bar[Any], Bar[str]) failed']",
    "Line 50: Unexpected errors ['Expected 2 type arguments for class `SubclassMe`, got 1.']",
    "Line 53: Unexpected errors ['assert_type(Any, str) failed']"
  ],
  "generics_paramspec_basic.py": [
    "Line 10: Expected 1 errors",
    "Line 15: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 31: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 18: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']"
  ],
  "generics_paramspec_components.py": [
    "Line 17: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 47: Unexpected errors ['assert_type(Any, int) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 53: Unexpected errors ['EXPECTED Callable[[Var[Args[_]], KwArgs[Kwargs[_]]], None] <: Callable[ParamSpec(P), None]']",
    "Line 56: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 66: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 68: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 74: Unexpected errors ['EXPECTED Callable[[Var[Args[_]], KwArgs[Kwargs[_]]], None] <: Callable[ParamSpec(P), None]']",
    "Line 79: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 82: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: call_infer: unsupported **kwargs argument to call']",
    "Line 85: Unexpected errors ['EXPECTED Callable[[Var[Args[_]], KwArgs[Kwargs[_]]], None] <: Callable[ParamSpec(P), None]']",
    "Line 89: Unexpected errors ['Answers::expr_infer wrong number of arguments to call', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 96: Unexpected errors ['EXPECTED Callable[[int, str], int] <: Callable[ParamSpec(@_), int]', 'EXPECTED Literal[1] <: Args[_]', \"EXPECTED Literal['A'] <: Args[_]\"]",
    "Line 97: Unexpected errors ['EXPECTED Callable[[int, str], int] <: Callable[ParamSpec(@_), int]', \"EXPECTED Literal['A'] <: Kwargs[_]\", 'EXPECTED Literal[1] <: Kwargs[_]']"
  ],
  "generics_paramspec_semantics.py": [
    "Line 98: Expected 1 errors",
    "Line 120: Expected 1 errors",
    "Line 127: Expected 1 errors",
    "Line 132: Expected 1 errors",
    "Line 137: Expected 1 errors",
    "Line 21: Unexpected errors ['EXPECTED Callable[[str, bool], int] <: Callable[ParamSpec(@_), int]']",
    "Line 22: Unexpected errors ['assert_type(Callable[ParamSpec(Any), str], Callable[[str, bool], str]) failed']",
    "Line 24: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 25: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 42: Unexpected errors ['EXPECTED Callable[[int, str], int] <: Callable[ParamSpec(@_), int]', 'EXPECTED Callable[[int, str], int] <: Callable[ParamSpec(@_), int]']",
    "Line 43: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 44: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 81: Unexpected errors ['EXPECTED Callable[[int], str] <: Callable[ParamSpec(@_), str]']",
    "Line 82: Unexpected errors ['untype, got list[type[int]]']",
    "Line 84: Unexpected errors ['assert_type(Callable[ParamSpec(Any), str], Callable[[int], str]) failed']",
    "Line 91: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 95: Unexpected errors ['EXPECTED Callable[[int, Var[bool]], int] <: Callable[ParamSpec(@_), int]']",
    "Line 96: Unexpected errors ['assert_type(Any, bool) failed']",
    "Line 97: Unexpected errors ['assert_type(Any, bool) failed']",
    "Line 101: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 106: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 107: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 112: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 113: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']",
    "Line 118: Unexpected errors ['assert_type(Any, bool) failed']",
    "Line 119: Unexpected errors ['assert_type(Any, bool) failed']",
    "Line 123: Unexpected errors ['TODO: Subscript(ExprSubscript - expr_infer, Callable type']"
  ],
  "generics_paramspec_specialization.py": [
    "Line 44: Expected 1 errors",
    "Line 28: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Concatenate[int, P2]`']",
    "Line 32: Unexpected errors ['untype, got list[type[bool] | type[int]]']",
    "Line 40: Unexpected errors ['untype, got list[@_]', 'untype, got list[@_]']",
    "Line 52: Unexpected errors ['untype, got list[type[bool] | type[int] | type[str]]']",
    "Line 53: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 58: Unexpected errors ['Expected 1 type argument for class `ClassC`, got 3.']",
    "Line 59: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']"
  ],
  "generics_scoping.py": [
    "Line 50: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 87: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors"
  ],
  "generics_self_advanced.py": [
    "Line 18: Unexpected errors ['assert_type(Callable[[], ParentA], ParentA) failed']",
    "Line 19: Unexpected errors ['assert_type(Callable[[], ParentA], ChildA) failed']",
    "Line 35: Unexpected errors ['assert_type(ChildB, Self) failed']",
    "Line 37: Unexpected errors ['assert_type(Any, Self) failed', 'Expected `list.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[list[Self]], SupportsIndex], _PyreReadOnly_[Self]] | Callable[[_PyreReadOnly_[list[Self]], slice[Error, Error, Error]], list[_PyreReadOnly_[Self]]] | Callable[[list[Self], SupportsIndex], Self] | Callable[[list[Self], slice[Error, Error, Error]], list[Self]]']",
    "Line 38: Unexpected errors ['assert_type(ParentB, Self) failed']",
    "Line 42: Unexpected errors ['assert_type(ChildB, type[Self]) failed']",
    "Line 44: Unexpected errors ['assert_type(Any, Self) failed', 'Expected `list.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[list[Self]], SupportsIndex], _PyreReadOnly_[Self]] | Callable[[_PyreReadOnly_[list[Self]], slice[Error, Error, Error]], list[_PyreReadOnly_[Self]]] | Callable[[list[Self], SupportsIndex], Self] | Callable[[list[Self], slice[Error, Error, Error]], list[Self]]']",
    "Line 45: Unexpected errors ['assert_type(ParentB, Self) failed']"
  ],
  "generics_self_attributes.py": [
    "Line 22: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 29: Unexpected errors ['EXPECTED OrdinalLinkedList <: Self | None', \"Unexpected keyword argument 'value'\", \"Unexpected keyword argument 'next'\"]"
  ],
  "generics_self_basic.py": [
    "Line 20: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 15: Unexpected errors ['Object of class `Shape` has no attribute `scale`']",
    "Line 27: Unexpected errors ['assert_type(Shape, type[Self]) failed']",
    "Line 28: Unexpected errors ['Expected a callable, got Shape']",
    "Line 37: Unexpected errors ['Expected a callable, got Shape']",
    "Line 40: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 52: Unexpected errors ['assert_type(Shape, Circle) failed']",
    "Line 54: Unexpected errors [\"Missing argument 'config'\", 'EXPECTED dict[@_, @_] <: Shape']",
    "Line 55: Unexpected errors ['assert_type(Shape, Circle) failed', \"Missing argument 'config'\", 'EXPECTED dict[@_, @_] <: Shape']"
  ],
  "generics_self_protocols.py": [
    "Line 57: Unexpected errors ['EXPECTED ReturnSelf <: ShapeProtocol']",
    "Line 58: Unexpected errors ['EXPECTED ReturnConcreteShape <: ShapeProtocol']"
  ],
  "generics_self_usage.py": [
    "Line 73: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 101: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 15: Unexpected errors ['Expected a callable, got ReturnsSelf']",
    "Line 18: Unexpected errors ['Expected a callable, got ReturnsSelf']",
    "Line 30: Unexpected errors ['EXPECTED ReturnsSelf <: type[ReturnsSelf]']",
    "Line 50: Unexpected errors ['EXPECTED Callable[[CallableAttribute], int] <: Callable[[Self], int]']",
    "Line 59: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 60: Unexpected errors [\"Missing argument 'flush'\", 'TODO: Answers::expr_infer attribute: `Self`.x']",
    "Line 63: Unexpected errors ['EXPECTED HasNestedFunction <: Self']",
    "Line 93: Unexpected errors ['Object of class `Foo3` has no attribute `child_value`']"
  ],
  "generics_syntax_compatibility.py": [],
  "generics_syntax_declarations.py": [
    "Line 19: Expected 1 errors",
    "Line 27: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 73: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 13: Unexpected errors ['TODO: TypeVarTuple(TypeParamTypeVarTuple - Answers::type_params', 'TODO: ParamSpec(TypeParamParamSpec - Answers::type_params']",
    "Line 14: Unexpected errors ['assert_type(type[T], TypeVar) failed']",
    "Line 15: Unexpected errors ['assert_type(type[Ts], TypeVarTuple) failed']",
    "Line 16: Unexpected errors ['assert_type(type[P], ParamSpec) failed']",
    "Line 33: Unexpected errors ['TODO: Answers::expr_infer attribute: `T`.capitalize']"
  ],
  "generics_syntax_infer_variance.py": [
    "Line 28: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 36: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 45: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 54: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]', 'Expected 0 positional argument(s)']",
    "Line 67: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 78: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 149: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']"
  ],
  "generics_syntax_scoping.py": [
    "Line 14: Expected 1 errors",
    "Line 18: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 52: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 61: Unexpected errors ['TODO: StmtNonlocal - Bindings::stmt']",
    "Line 66: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']",
    "Line 67: Unexpected errors ['assert_type(str, int) failed']",
    "Line 85: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 90: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 102: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 106: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 111: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 116: Unexpected errors ['assert_type(int, TypeVar) failed']",
    "Line 121: Unexpected errors ['assert_type(Literal[0+3j], complex) failed']",
    "Line 124: Unexpected errors ['assert_type(Literal[0+3j], complex) failed']"
  ],
  "generics_type_erasure.py": [
    "Line 15: Unexpected errors ['EXPECTED T | None <: T']",
    "Line 56: Unexpected errors ['assert_type(Any, bytes) failed']"
  ],
  "generics_typevartuple_args.py": [
    "Line 33: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 20: Unexpected errors ['assert_type(tuple[Any], tuple[int, str]) failed']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 31: Unexpected errors ['assert_type(tuple[Any], tuple[()]) failed']",
    "Line 32: Unexpected errors ['assert_type(tuple[Any], tuple[int, str]) failed']",
    "Line 42: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 51: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 62: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 70: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_basic.py": [
    "Line 52: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 89: Expected 1 errors",
    "Line 99: Expected 1 errors",
    "Line 100: Expected 1 errors",
    "Line 12: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 23: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 24: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 36: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType', 'EXPECTED tuple[Error, Error] <: tuple[Error]', 'Expected a callable, got NewType', 'Expected a callable, got NewType']",
    "Line 37: Unexpected errors ['Expected 0 type arguments for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'EXPECTED tuple[Error, Error, Error] <: tuple[Error]', 'Expected a callable, got NewType', 'Expected a callable, got NewType', 'Expected a callable, got NewType']",
    "Line 38: Unexpected errors ['Expected 0 type arguments for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 39: Unexpected errors ['EXPECTED tuple[Error, Error, Error, Error] <: tuple[Error]', 'Expected a callable, got NewType', 'Expected a callable, got NewType', 'Expected a callable, got NewType', 'Expected a callable, got NewType']",
    "Line 54: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 75: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 84: Unexpected errors ['assert_type(tuple[Any], tuple[int]) failed']",
    "Line 93: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 97: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'untype, got NewType', 'Expected 0 type arguments for class `Array`, got 1.', 'untype, got NewType', 'Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']"
  ],
  "generics_typevartuple_callable.py": [
    "Line 17: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['EXPECTED Callable[[int, str], None] <: Callable[[Error], None]', \"EXPECTED tuple[Literal[0], Literal['']] <: tuple[Error]\"]",
    "Line 29: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 41: Unexpected errors ['assert_type(tuple[Any, Any], tuple[str, int, complex]) failed', 'EXPECTED Callable[[int, str, int, complex], tuple[complex, str, int]] <: Callable[[int, Error, @_], tuple[@_, Error]]']",
    "Line 42: Unexpected errors ['assert_type(tuple[Any, Any], tuple[str]) failed', 'EXPECTED Callable[[int, str], tuple[str]] <: Callable[[int, Error, @_], tuple[@_, Error]]']",
    "Line 45: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 49: Unexpected errors ['assert_type(tuple[Any, Any], tuple[float, str, complex]) failed']"
  ],
  "generics_typevartuple_concat.py": [
    "Line 22: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 26: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 30: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 34: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 type arguments for class `Array`, got 3.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got NewType']",
    "Line 38: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 40: Unexpected errors ['Expected 0 type arguments for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 42: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 44: Unexpected errors ['Expected 0 type arguments for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 47: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 51: Unexpected errors [\"EXPECTED tuple[Literal[True], Literal['a']] <: tuple[Error]\"]",
    "Line 52: Unexpected errors ['assert_type(tuple[int, Any], tuple[int, bool, str]) failed']",
    "Line 55: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 56: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_overloads.py": [
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 18: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'Expected 0 type arguments for class `Array`, got 2.']",
    "Line 22: Unexpected errors ['Expected 0 type arguments for class `Array`, got 3.', 'Expected 0 type arguments for class `Array`, got 3.']",
    "Line 29: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'Expected 0 type arguments for class `Array`, got 3.']",
    "Line 30: Unexpected errors ['assert_type(Array | Any, Array) failed', \"Missing argument 'self'\", 'Expected 0 type arguments for class `Array`, got 2.']",
    "Line 31: Unexpected errors ['assert_type(Array | Any, Array) failed', \"Missing argument 'self'\", 'Expected 0 type arguments for class `Array`, got 3.']"
  ],
  "generics_typevartuple_specialization.py": [
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 24: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 28: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 33: Unexpected errors ['Expected 0 type arguments for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 41: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 42: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 45: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array]]]\"]",
    "Line 46: Unexpected errors ['assert_type(Any, tuple[int, float, bool]) failed']",
    "Line 47: Unexpected errors ['assert_type(Any, tuple[str, Array]) failed', 'Expected 0 type arguments for class `Array`, got 1.', 'untype, got NewType']",
    "Line 50: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array]]]\"]",
    "Line 51: Unexpected errors ['assert_type(Any, tuple[int]) failed']",
    "Line 52: Unexpected errors ['assert_type(Any, tuple[str, Array]) failed']",
    "Line 59: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 63: Unexpected errors ['Expected 1 type argument for class `Array2`, got 2.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 64: Unexpected errors ['Expected 1 type argument for class `Array2`, got 2.']",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Array1D, type[Array2[Error]]]\"]",
    "Line 68: Unexpected errors ['Expected 1 type argument for class `Array2`, got 2.']",
    "Line 69: Unexpected errors ['assert_type(Any, Array2[Any]) failed', 'Expected 1 type argument for class `Array2`, got 2.']",
    "Line 76: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[Error]]]\"]",
    "Line 80: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[Error]]]\"]",
    "Line 89: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 92: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], Error]]]\"]",
    "Line 93: Unexpected errors ['assert_type(Any, tuple[str, int]) failed']",
    "Line 94: Unexpected errors ['assert_type(Any, tuple[float]) failed']",
    "Line 95: Unexpected errors ['assert_type(tuple[TypeVar[T], Any], tuple[Any, Any]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 101: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 102: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, Error]]]\"]",
    "Line 103: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, Error]]]\"]",
    "Line 108: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleGeneric, type[tuple[int, TypeVar[T]]]]\"]",
    "Line 117: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 118: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 119: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 120: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 125: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 130: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 134: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\"]",
    "Line 135: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[()], str, bool]) failed']",
    "Line 136: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[str], bool, float]) failed']",
    "Line 137: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[str, bool], float, int]) failed']",
    "Line 140: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 143: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\", 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 147: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\"]",
    "Line 148: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any, Any], tuple[tuple[()], str, bool, float]) failed']",
    "Line 149: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any, Any], tuple[tuple[bool], str, float, int]) failed']",
    "Line 152: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 153: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\"]",
    "Line 157: Unexpected errors ['assert_type(Any, tuple[Any, int]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 158: Unexpected errors ['assert_type(Any, tuple[Any, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 159: Unexpected errors ['assert_type(Any, tuple[Any, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 162: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_unpack.py": [
    "Line 30: Expected 1 errors",
    "Line 17: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 21: Unexpected errors ['Expected 0 type arguments for class `Array`, got 3.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got NewType']",
    "Line 26: Unexpected errors ['Expected 0 type arguments for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType', 'Expected 0 type arguments for class `Array`, got 1.', 'untype, got NewType']",
    "Line 36: Unexpected errors ['Expected 0 type arguments for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 40: Unexpected errors ['Expected 0 type arguments for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 44: Unexpected errors ['Expected 0 type arguments for class `Array`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_upper_bound.py": [
    "Line 24: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 37: Unexpected errors ['assert_type(list[Any], list[int]) failed']",
    "Line 38: Unexpected errors ['assert_type(set[Any], set[int]) failed']"
  ],
  "generics_variance.py": [
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 163: Expected 1 errors",
    "Line 167: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Lines 125, 126: Expected error (tag 'CoContra_Child2')",
    "Lines 131, 132: Expected error (tag 'CoContra_Child3')",
    "Lines 141, 142: Expected error (tag 'CoContra_Child5')",
    "Lines 195, 196: Expected error (tag 'ContraToContraToContra_WithTA')",
    "Line 39: Unexpected errors ['EXPECTED ImmutableList[Manager] <: ImmutableList[Employee]']"
  ],
  "generics_variance_inference.py": [
    "Line 26: Unexpected errors ['EXPECTED ClassA[float, int, int] <: ClassA[float, int, float]']",
    "Line 29: Unexpected errors ['EXPECTED ClassA[int, float, float] <: ClassA[int, int, float]']",
    "Line 40: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 48: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 57: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 66: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]', 'Expected 0 positional argument(s)']",
    "Line 79: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 150: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']",
    "Line 182: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 193: Unexpected errors ['EXPECTED ShouldBeContravariant2[float] <: ShouldBeContravariant2[int]']"
  ],
  "historical_positional.py": [
    "Line 18: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 43: Expected 1 errors"
  ],
  "literals_interactions.py": [
    "Line 49: Unexpected errors ['assert_type(Any, IO[str]) failed']",
    "Line 50: Unexpected errors ['assert_type(Any, IO[bytes]) failed']",
    "Line 51: Unexpected errors ['assert_type(Any, IO[Any]) failed']",
    "Line 71: Unexpected errors ['EXPECTED Matrix[Literal[3], Literal[7]] <: Matrix[Literal[3], TypeVar[C]]']",
    "Line 72: Unexpected errors ['assert_type(Matrix[Literal[2], TypeVar[C]], Matrix[Literal[2], Literal[7]]) failed']",
    "Line 87: Unexpected errors ['assert_type(Status | str, Literal[Status.SUCCESS]) failed']",
    "Line 89: Unexpected errors ['assert_type(Status | str, Literal[Status.INVALID_DATA]) failed']",
    "Line 91: Unexpected errors ['assert_type(Status | str, Literal[Status.FATAL_ERROR]) failed']",
    "Line 93: Unexpected errors ['assert_type(Status | str, str) failed']",
    "Line 106: Unexpected errors [\"EXPECTED str <: Literal['ABORTED', 'MALFORMED']\"]",
    "Line 109: Unexpected errors [\"EXPECTED str <: Literal['PENDING']\"]"
  ],
  "literals_literalstring.py": [
    "Line 120: Expected 1 errors",
    "Line 48: Unexpected errors ['assert_type(Any, LiteralString) failed', 'Expected `__add__` to be a callable, got Callable[[LiteralString, LiteralString], LiteralString] | Callable[[str, str], str]']",
    "Line 52: Unexpected errors ['assert_type(LiteralString | str, LiteralString) failed', 'Expected 1 more positional argument(s)', 'EXPECTED tuple[LiteralString, LiteralString] <: LiteralString', 'EXPECTED tuple[LiteralString, LiteralString] <: str']",
    "Line 53: Unexpected errors ['assert_type(LiteralString | str, str) failed', 'Expected 1 more positional argument(s)', 'EXPECTED tuple[LiteralString, str] <: LiteralString', 'EXPECTED tuple[LiteralString, str] <: str', 'Expected 0 positional argument(s)']",
    "Line 57: Unexpected errors ['Object of class `str` has no attribute `__iadd__`']",
    "Line 58: Unexpected errors ['Object of class `str` has no attribute `__iadd__`']",
    "Line 63: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 68: Unexpected errors ['assert_type(Any, str) failed', 'Expected 0 positional argument(s)']",
    "Line 111: Unexpected errors [\"assert_type(str, Literal['hello']) failed\"]",
    "Line 116: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 130: Unexpected errors ['EXPECTED Container[str] <: Container[LiteralString]']",
    "Line 165: Unexpected errors ['assert_type(Any, C) failed']",
    "Line 166: Unexpected errors ['assert_type(Any, B) failed']",
    "Line 167: Unexpected errors ['assert_type(Any, A) failed', 'Expected 0 positional argument(s)']",
    "Line 175: Unexpected errors ['EXPECTED Sequence[LiteralString] <: Sequence[str]']"
  ],
  "literals_parameterizations.py": [
    "Line 46: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 26: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr']",
    "Line 33: Unexpected errors ['TODO: Name(ExprName - Lit::from_expr', 'TODO: Name(ExprName - Lit::from_expr', 'TODO: Name(ExprName - Lit::from_expr', 'TODO: Name(ExprName - Lit::from_expr']",
    "Line 35: Unexpected errors ['TODO: Subscript(ExprSubscript - Lit::from_expr', 'TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr']"
  ],
  "literals_semantics.py": [
    "Line 38: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr', 'Could not find name `foo`', 'TODO: Name(ExprName - Lit::from_expr']",
    "Line 39: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr']"
  ],
  "namedtuples_define_class.py": [
    "Line 59: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 21: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 23: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 24: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 25: Unexpected errors ['assert_type(Any, str) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 26: Unexpected errors ['assert_type(Any, str) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 27: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 28: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 29: Unexpected errors ['assert_type(Any, tuple[int, int]) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 30: Unexpected errors ['assert_type(Any, tuple[int, int, str]) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 35: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 38: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\"]",
    "Line 41: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\", \"Unexpected keyword argument 'units'\"]",
    "Line 72: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 73: Unexpected errors ['EXPECTED PointWithName <: tuple[int, int, str]']",
    "Line 93: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 94: Unexpected errors ['assert_type(Property[Any], Property[float]) failed']",
    "Line 95: Unexpected errors ['assert_type(Any, float) failed', 'Object of class `Property` has no attribute `__getitem__`']",
    "Line 96: Unexpected errors ['assert_type(Any, float) failed']"
  ],
  "namedtuples_define_functional.py": [
    "Line 36: Expected 1 errors",
    "Line 37: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 43: Expected 1 errors",
    "Line 14: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 15: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 18: Unexpected errors [\"EXPECTED tuple[Literal['x'], Literal['y']] <: Iterable[str] | str\"]",
    "Line 19: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 20: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 24: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 25: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 29: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 30: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 33: Unexpected errors ['Expected a callable, got type[NamedTuple]']",
    "Line 39: Unexpected errors ['Expected a callable, got type[NamedTuple]']",
    "Line 57: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT4, type[tuple[Any, ...]]]']",
    "Line 64: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']",
    "Line 65: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']"
  ],
  "namedtuples_type_compat.py": [
    "Line 19: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\", \"Unexpected keyword argument 'units'\"]",
    "Line 20: Unexpected errors ['EXPECTED Point <: tuple[int, int, str]']",
    "Line 21: Unexpected errors ['EXPECTED Point <: tuple[Any, ...]']",
    "Line 27: Unexpected errors ['EXPECTED Point <: tuple[float, float, str]']"
  ],
  "namedtuples_usage.py": [
    "Line 40: Expected 1 errors",
    "Line 19: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 27: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 28: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 29: Unexpected errors ['assert_type(Any, str) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 30: Unexpected errors ['assert_type(Any, str) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 31: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 32: Unexpected errors ['assert_type(Any, int) failed', 'Object of class `Point` has no attribute `__getitem__`']",
    "Line 48: Unexpected errors ['Class `Point` is not iterable']",
    "Line 49: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 50: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 60: Unexpected errors ['Expected 0 positional argument(s)']",
    "Line 61: Unexpected errors ['Class `PointWithName` is not iterable']"
  ],
  "narrowing_typeguard.py": [
    "Line 102: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 13: Unexpected errors ['EXPECTED bool <: TypeGuard[tuple[T, T]]', 'EXPECTED tuple[T, ...] <: _PyreReadOnly_[Sized]']",
    "Line 17: Unexpected errors ['assert_type(tuple[str, ...], tuple[str, str]) failed']",
    "Line 24: Unexpected errors ['EXPECTED bool <: TypeGuard[list[str]]']",
    "Line 25: Unexpected errors ['EXPECTED bool <: TypeGuard[list[str]]', 'EXPECTED Generator[bool, None, None] <: Iterable[object]', 'EXPECTED type[str] <: UnionType | type | tuple[Unknown, ...]', 'Expected `list.__iter__` to be a callable, got Callable[[_PyreReadOnly_[list[object]]], Iterator[_PyreReadOnly_[object]]] | Callable[[list[object]], Iterator[object]]']",
    "Line 28: Unexpected errors ['EXPECTED bool <: TypeGuard[set[T]]', 'EXPECTED Generator[bool, None, None] <: Iterable[object]']",
    "Line 32: Unexpected errors ['assert_type(set[object], set[int]) failed']",
    "Line 41: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 45: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 49: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 52: Unexpected errors ['EXPECTED bool <: TypeGuard[A]', 'Expected a callable, got type[type]']",
    "Line 55: Unexpected errors ['EXPECTED bool <: TypeGuard[T_A]', 'Expected a callable, got type[type]']",
    "Line 69: Unexpected errors ['assert_type(object, int) failed']",
    "Line 73: Unexpected errors ['assert_type(object, int) failed']",
    "Line 77: Unexpected errors ['assert_type(object, int) failed']",
    "Line 81: Unexpected errors ['assert_type(object, int) failed']",
    "Line 85: Unexpected errors ['assert_type(object, int) failed']",
    "Line 89: Unexpected errors ['assert_type(object, B) failed']",
    "Line 93: Unexpected errors ['assert_type(object, B) failed']",
    "Line 103: Unexpected errors ['EXPECTED Literal[False] <: TypeGuard[int]']",
    "Line 108: Unexpected errors ['EXPECTED Literal[False] <: TypeGuard[int]']",
    "Line 124: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 147: Unexpected errors ['EXPECTED Callable[[object], TypeGuard[int]] <: CallableBoolProto']",
    "Line 159: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 163: Unexpected errors ['EXPECTED bool <: TypeGuard[bool]', 'EXPECTED type[bool] <: UnionType | type | tuple[Unknown, ...]']"
  ],
  "narrowing_typeis.py": [
    "Line 105: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 199: Expected 1 errors",
    "Line 15: Unexpected errors ['EXPECTED bool <: TypeIs[tuple[T, T]]', 'EXPECTED tuple[T, ...] <: _PyreReadOnly_[Sized]']",
    "Line 19: Unexpected errors ['assert_type(tuple[str, ...], tuple[str, str]) failed']",
    "Line 28: Unexpected errors ['EXPECTED bool <: TypeIs[Awaitable[Any]]', 'EXPECTED type[Awaitable] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 35: Unexpected errors ['Expression is not awaitable']",
    "Line 38: Unexpected errors ['assert_type(Awaitable[int] | int, int) failed']",
    "Line 45: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 49: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 53: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 56: Unexpected errors ['EXPECTED bool <: TypeIs[A]', 'Expected a callable, got type[type]']",
    "Line 59: Unexpected errors ['EXPECTED bool <: TypeIs[T_A]', 'Expected a callable, got type[type]']",
    "Line 72: Unexpected errors ['assert_type(object, int) failed']",
    "Line 76: Unexpected errors ['assert_type(object, int) failed']",
    "Line 80: Unexpected errors ['assert_type(object, int) failed']",
    "Line 84: Unexpected errors ['assert_type(object, int) failed']",
    "Line 88: Unexpected errors ['assert_type(object, int) failed']",
    "Line 92: Unexpected errors ['assert_type(object, B) failed']",
    "Line 96: Unexpected errors ['assert_type(object, B) failed']",
    "Line 106: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 111: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 128: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 151: Unexpected errors ['EXPECTED Callable[[object], TypeIs[int]] <: CallableBoolProto']",
    "Line 163: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 166: Unexpected errors ['EXPECTED bool <: TypeGuard[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 183: Unexpected errors ['EXPECTED bool <: TypeIs[int]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 187: Unexpected errors ['EXPECTED bool <: TypeIs[bool]', 'EXPECTED type[bool] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 196: Unexpected errors ['EXPECTED bool <: TypeIs[str]', 'EXPECTED type[str] <: UnionType | type | tuple[Unknown, ...]']",
    "Line 200: Unexpected errors ['EXPECTED bool <: TypeIs[list[int]]', 'EXPECTED Generator[bool, None, None] <: Iterable[object]', 'EXPECTED type[int] <: UnionType | type | tuple[Unknown, ...]', 'TODO: Answers::solve_binding - Binding::IterableValue']"
  ],
  "overloads_basic.py": [
    "Lines 62, 63: Expected error (tag 'func1')",
    "Lines 74, 75: Expected error (tag 'func2')",
    "Line 35: Unexpected errors ['assert_type(Any, int) failed', 'Expected `Bytes.__getitem__` to be a callable, got Callable[[Bytes, int], int] | Callable[[Bytes, int | slice[Error, Error, Error]], bytes | int] | Callable[[Bytes, slice[Error, Error, Error]], bytes]']",
    "Line 36: Unexpected errors ['assert_type(Any, bytes) failed', 'Expected `Bytes.__getitem__` to be a callable, got Callable[[Bytes, int], int] | Callable[[Bytes, int | slice[Error, Error, Error]], bytes | int] | Callable[[Bytes, slice[Error, Error, Error]], bytes]']"
  ],
  "protocols_class_objects.py": [
    "Line 29: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 30: Unexpected errors ['EXPECTED type[Concrete] <: type[Proto]']",
    "Line 35: Unexpected errors ['EXPECTED type[Concrete] <: type[Proto]']",
    "Line 59: Unexpected errors ['EXPECTED type[ConcreteA] <: ProtoA2']",
    "Line 105: Unexpected errors ['EXPECTED type[ConcreteC1] <: ProtoC2']",
    "Line 109: Unexpected errors ['EXPECTED type[ConcreteC3] <: ProtoC2']"
  ],
  "protocols_definition.py": [
    "Line 27: Unexpected errors [\"Missing argument 'mode'\"]",
    "Line 29: Unexpected errors ['EXPECTED IO[Any] <: SupportsClose', 'EXPECTED Resource <: SupportsClose']",
    "Line 39: Unexpected errors ['EXPECTED None <: int']",
    "Line 79: Unexpected errors ['EXPECTED Concrete <: Template']",
    "Line 102: Unexpected errors ['EXPECTED Literal[2] <: float']",
    "Line 113: Unexpected errors ['EXPECTED Concrete2_Good1 <: Template2']",
    "Line 148: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 155: Unexpected errors ['EXPECTED Concrete3_Good1 <: Template3']",
    "Line 172: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 182: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 190: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 194: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 199: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 211: Unexpected errors ['EXPECTED Concrete4_Good1 <: Template4']",
    "Line 212: Unexpected errors ['EXPECTED Concrete4_Good2 <: Template4']",
    "Line 213: Unexpected errors ['EXPECTED Concrete4_Good3 <: Template4']",
    "Line 214: Unexpected errors ['EXPECTED Concrete4_Good4 <: Template4']",
    "Line 215: Unexpected errors ['EXPECTED Concrete4_Good5 <: Template4']",
    "Line 216: Unexpected errors ['EXPECTED Concrete4_Good6 <: Template4']",
    "Line 217: Unexpected errors ['EXPECTED Concrete4_Good7 <: Template4']",
    "Line 245: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 251: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 266: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 271: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 277: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 280: Unexpected errors ['EXPECTED Concrete5_Good1 <: Template5']",
    "Line 281: Unexpected errors ['EXPECTED Concrete5_Good2 <: Template5']",
    "Line 282: Unexpected errors ['EXPECTED Concrete5_Good3 <: Template5']",
    "Line 283: Unexpected errors ['EXPECTED Concrete5_Good4 <: Template5']",
    "Line 284: Unexpected errors ['EXPECTED Concrete5_Good5 <: Template5']",
    "Line 305: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 313: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 318: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 324: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 328: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 333: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 336: Unexpected errors ['EXPECTED Concrete6_Good1 <: Template6']",
    "Line 337: Unexpected errors ['EXPECTED Concrete6_Good2 <: Template6']",
    "Line 338: Unexpected errors ['EXPECTED Concrete6_Good3 <: Template6']"
  ],
  "protocols_explicit.py": [
    "Line 56: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 165: Expected 1 errors",
    "Line 39: Unexpected errors ['EXPECTED ImplicitColor <: PColor']"
  ],
  "protocols_generic.py": [
    "Line 33: Unexpected errors ['Expected `list.__iter__` to be a callable, got Callable[[_PyreReadOnly_[list[int]]], Iterator[_PyreReadOnly_[int]]] | Callable[[list[int]], Iterator[int]]']",
    "Line 39: Unexpected errors ['EXPECTED Concrete1 <: Proto1[str, int]']",
    "Line 55: Unexpected errors ['EXPECTED Box[int] <: Box[float]']",
    "Line 65: Unexpected errors ['EXPECTED Sender[float] <: Sender[int]']",
    "Line 87: Unexpected errors ['TODO: Answers::expr_infer attribute: `GenericHasParent`.get_parent']",
    "Line 144: Unexpected errors ['EXPECTED ConcreteHasProperty1 <: HasPropertyProto']",
    "Line 145: Unexpected errors ['EXPECTED ConcreteHasProperty2 <: HasPropertyProto']"
  ],
  "protocols_merging.py": [
    "Line 67: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 46: Unexpected errors ['EXPECTED SCConcrete1 <: SizedAndClosable1']",
    "Line 47: Unexpected errors ['EXPECTED SCConcrete1 <: SizedAndClosable2']",
    "Line 49: Unexpected errors ['EXPECTED SizedAndClosable3 <: SizedAndClosable2']",
    "Line 50: Unexpected errors ['EXPECTED SCConcrete1 <: Sized']",
    "Line 59: Unexpected errors ['EXPECTED SizedAndClosable1 <: SizedAndClosable2']",
    "Line 60: Unexpected errors ['EXPECTED SizedAndClosable2 <: SizedAndClosable1']"
  ],
  "protocols_modules.py": [
    "Line 10: Unexpected errors ['Could not find import of `_protocols_modules1`, Could not find path for `_protocols_modules1`']",
    "Line 11: Unexpected errors ['Could not find import of `_protocols_modules2`, Could not find path for `_protocols_modules2`']",
    "Line 25: Unexpected errors ['EXPECTED Module[_protocols_modules1] <: Options1']",
    "Line 47: Unexpected errors ['EXPECTED Module[_protocols_modules2] <: Reporter1']"
  ],
  "protocols_recursive.py": [
    "Line 25: Unexpected errors ['EXPECTED SimpleTree <: Traversable']",
    "Line 38: Unexpected errors ['EXPECTED Tree[float] <: Traversable']",
    "Line 80: Unexpected errors ['EXPECTED ImplB <: ProtoA[Never, @_]']",
    "Line 81: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "protocols_runtime_checkable.py": [
    "Line 23: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 88: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "protocols_self.py": [
    "Line 32: Unexpected errors ['EXPECTED One <: Copyable']",
    "Line 33: Unexpected errors ['EXPECTED Other <: Copyable']",
    "Line 54: Unexpected errors ['EXPECTED C1[str] <: P1Parent[str]']",
    "Line 55: Unexpected errors ['EXPECTED C1[str] <: P1Child[str]']",
    "Line 72: Unexpected errors ['EXPECTED C2[str] <: P2Parent[str]']",
    "Line 73: Unexpected errors ['EXPECTED C2[str] <: P2Child[str]']"
  ],
  "protocols_subtyping.py": [
    "Line 16: Expected 1 errors",
    "Line 37: Unexpected errors ['EXPECTED Concrete2 <: Proto2']",
    "Line 54: Unexpected errors ['EXPECTED Proto3 <: Proto2']",
    "Line 77: Unexpected errors ['EXPECTED Proto5[int] <: Proto4[int, int]']",
    "Line 78: Unexpected errors ['EXPECTED Proto4[int, int] <: Proto5[int]']",
    "Line 98: Unexpected errors ['EXPECTED Proto6[float, float] <: Proto7[object, int]']",
    "Line 99: Unexpected errors ['EXPECTED Proto6[float, float] <: Proto7[float, float]']",
    "Line 100: Unexpected errors ['EXPECTED Proto6[float, float] <: Proto7[complex, int]']",
    "Line 128: Unexpected errors ['EXPECTED DefaultJob <: SupportsExit | SupportsQuit']",
    "Line 142: Unexpected errors ['EXPECTED tuple[Literal[1], Literal[2], Literal[3]] <: HashableFloats']"
  ],
  "protocols_variance.py": [
    "Line 21: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 104: Expected 1 errors"
  ],
  "qualifiers_annotated.py": [
    "Line 49: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 36: Unexpected errors ['TODO: NoneLiteral(ExprNoneLiteral - Lit::from_expr', 'Could not find name `x`']",
    "Line 60: Unexpected errors ['Could not find name `x`']",
    "Line 81: Unexpected errors ['Expected a callable, got type[T]']",
    "Line 98: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[int]`']",
    "Line 100: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Final[int]`']",
    "Line 109: Unexpected errors ['untype, got object']",
    "Line 110: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 112: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[int]`']"
  ],
  "qualifiers_final_annotation.py": [
    "Line 16: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 134: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 141: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 131: Unexpected errors ['Expected a callable, got type[NamedTuple]']",
    "Line 139: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']"
  ],
  "qualifiers_final_decorator.py": [
    "Line 21: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 118: Expected 1 errors",
    "Lines 59, 60: Expected error (tag 'method2')",
    "Lines 63, 64: Expected error (tag 'method3')",
    "Lines 67, 75: Expected error (tag 'method4')",
    "Lines 80, 89: Expected error (tag 'Derived3')",
    "Lines 84, 85, 86: Expected error (tag 'Derived3-2')",
    "Lines 94, 102: Expected error (tag 'Derived4')",
    "Lines 125, 126: Expected error (tag 'func')",
    "Line 8: Unexpected errors ['Could not find import of `_qualifiers_final_decorator`, Could not find path for `_qualifiers_final_decorator`', 'Could not import `Base3` from `_qualifiers_final_decorator`', 'Could not import `Base4` from `_qualifiers_final_decorator`']"
  ],
  "specialtypes_any.py": [
    "Line 62: Unexpected errors ['assert_type(tuple[Any], tuple[Any, ...]) failed']",
    "Line 64: Unexpected errors ['EXPECTED tuple[Error] <: tuple[str, ...]']",
    "Line 65: Unexpected errors ['EXPECTED tuple[Error] <: tuple[int, ...]']",
    "Line 72: Unexpected errors ['assert_type(Callable, Callable[..., Any]) failed']",
    "Line 74: Unexpected errors ['EXPECTED Callable <: Callable[[], Any]']",
    "Line 75: Unexpected errors ['EXPECTED Callable <: Callable[[int, str], None]']",
    "Line 87: Unexpected errors ['Object of class `ClassA` has no attribute `method2`']",
    "Line 88: Unexpected errors ['Class `ClassA` has no class attribute `method3`']"
  ],
  "specialtypes_never.py": [
    "Line 19: Expected 1 errors",
    "Line 16: Unexpected errors ['EXPECTED None <: NoReturn', 'Expected 0 positional argument(s)']",
    "Line 21: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 32: Unexpected errors [\"EXPECTED Literal['whatever works'] <: int\"]",
    "Line 77: Unexpected errors ['EXPECTED None <: Never']",
    "Line 96: Unexpected errors ['EXPECTED ClassB[Never] <: ClassB[U]']"
  ],
  "specialtypes_none.py": [
    "Line 24: Unexpected errors ['EXPECTED None <: Hashable']",
    "Line 30: Unexpected errors ['TODO: Answers::expr_infer attribute: `None`.__class__']",
    "Line 31: Unexpected errors ['TODO: Answers::expr_infer attribute: `None`.__doc__']",
    "Line 32: Unexpected errors ['TODO: Answers::expr_infer attribute: `None`.__eq__']",
    "Line 39: Unexpected errors ['TODO: Answers::expr_infer attribute: `None`.__class__']",
    "Line 40: Unexpected errors ['Expected a callable, got type[type]']"
  ],
  "specialtypes_promotions.py": [
    "Line 7: Unexpected errors ['EXPECTED Literal[1] <: float']",
    "Line 8: Unexpected errors ['EXPECTED Literal[1.2] <: complex']",
    "Line 9: Unexpected errors ['EXPECTED Literal[1] <: complex']",
    "Line 16: Unexpected errors ['Object of class `float` has no attribute `numerator`']"
  ],
  "specialtypes_type.py": [
    "Line 70: Expected 1 errors",
    "Line 28: Unexpected errors ['Expected a callable, got type']",
    "Line 39: Unexpected errors ['Expected a callable, got type[U]']",
    "Line 42: Unexpected errors ['EXPECTED type[TeamUser] <: type']",
    "Line 44: Unexpected errors ['assert_type(Any, TeamUser) failed', 'EXPECTED type[TeamUser] <: type[@_]']",
    "Line 51: Unexpected errors ['Expected a callable, got type[BasicUser | ProUser]']",
    "Line 54: Unexpected errors ['EXPECTED type[BasicUser] <: type[BasicUser | ProUser]']",
    "Line 55: Unexpected errors ['EXPECTED type[ProUser] <: type[BasicUser | ProUser]']",
    "Line 68: Unexpected errors ['EXPECTED type[User] <: type[@_]']",
    "Line 69: Unexpected errors ['EXPECTED type[tuple] <: type[@_]']",
    "Line 84: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 87: Unexpected errors ['EXPECTED type[type] <: type']",
    "Line 98: Unexpected errors ['assert_type(Callable[[], tuple[type, ...]], tuple[type, ...]) failed']",
    "Line 99: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 100: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 102: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 106: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed', 'TODO: Answers::expr_infer attribute: `Type`.__mro__']",
    "Line 107: Unexpected errors ['TODO: Answers::expr_infer attribute: `Type`.unknown']",
    "Line 108: Unexpected errors ['TODO: Answers::expr_infer attribute: `Type`.unknown']",
    "Line 110: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 116: Unexpected errors ['assert_type(Any, str) failed', 'Class `object` has no class attribute `__name__`']",
    "Line 119: Unexpected errors ['assert_type(Any, str) failed', 'Class `object` has no class attribute `__name__`']",
    "Line 137: Unexpected errors ['assert_type(Type, type[Any]) failed']",
    "Line 139: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 152: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA7, type[type[TypeVar[T]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA8, type[type[TypeVar[T]]]]\"]",
    "Line 160: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 161: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 165: Unexpected errors ['EXPECTED type <: Callable[..., Any]']",
    "Line 166: Unexpected errors ['EXPECTED type <: Callable[[int, int], int]']",
    "Line 169: Unexpected errors ['EXPECTED type <: type[int]']",
    "Line 170: Unexpected errors ['EXPECTED type <: type[Any]']",
    "Line 175: Unexpected errors ['EXPECTED type <: type[T]']"
  ],
  "tuples_type_compat.py": [
    "Line 14: Unexpected errors ['EXPECTED tuple[int, int] <: tuple[float, complex]']",
    "Line 22: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 28: Unexpected errors ['EXPECTED tuple[int] <: tuple[int, Error]']",
    "Line 47: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 59: Unexpected errors ['EXPECTED tuple[@_] <: tuple[int, int]', 'Expected 0 positional argument(s)']",
    "Line 71: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 74: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int]) failed']",
    "Line 78: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, int] | tuple[str, str]) failed']",
    "Line 82: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, str, int]) failed']",
    "Line 91: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 92: Unexpected errors ['TODO: StmtMatch - Bindings::stmt']",
    "Line 113: Unexpected errors ['TODO: StmtMatch - Bindings::stmt']",
    "Line 134: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 139: Unexpected errors ['assert_type(Sequence[int | Any], Sequence[int | str]) failed']",
    "Line 143: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 146: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1]] <: tuple[int, Error]']",
    "Line 148: Unexpected errors [\"EXPECTED tuple[Literal[1], Literal[''], Literal['']] <: tuple[int, Error]\"]",
    "Line 153: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1], Literal[2]] <: tuple[int, Error, int]']",
    "Line 155: Unexpected errors [\"EXPECTED tuple[Literal[1], Literal[''], Literal[''], Literal[2]] <: tuple[int, Error, int]\"]",
    "Line 159: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1]] <: tuple[Error, int]']",
    "Line 161: Unexpected errors [\"EXPECTED tuple[Literal[''], Literal[''], Literal[1]] <: tuple[Error, int]\"]",
    "Line 167: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, str, Error]']",
    "Line 169: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 170: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, str, Error]']",
    "Line 172: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, Error, str]']",
    "Line 173: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 174: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "tuples_type_form.py": [],
  "tuples_unpacked.py": [
    "Line 59: Expected 1 errors",
    "Lines 60, 61: Expected error (tag 't14')",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 17: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[int, bool, bool, str]) failed']",
    "Line 18: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[Any, bool, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 19: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[int, bool, Any]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 26: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 31: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 0 positional argument(s)', 'Expected 0 positional argument(s)']",
    "Line 33: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 38: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 39: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 49: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 50: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "typeddicts_alt_syntax.py": [
    "Line 45: Expected 1 errors",
    "Line 10: Unexpected errors ['Expected a callable, got object']",
    "Line 14: Unexpected errors ['Expected a callable, got object']"
  ],
  "typeddicts_class_syntax.py": [
    "Line 29: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 10: Unexpected errors ['untype, got object']",
    "Line 18: Unexpected errors ['untype, got object']",
    "Line 25: Unexpected errors ['untype, got object']",
    "Line 57: Unexpected errors ['untype, got object']",
    "Line 64: Unexpected errors ['untype, got object']",
    "Line 68: Unexpected errors ['untype, got object']",
    "Line 72: Unexpected errors ['untype, got object']",
    "Line 76: Unexpected errors ['untype, got object']"
  ],
  "typeddicts_final.py": [
    "Line 10: Unexpected errors ['untype, got object']",
    "Line 19: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie']",
    "Line 20: Unexpected errors ['Object of class `Movie` has no attribute `__getitem__`']",
    "Line 26: Unexpected errors ['Object of class `Movie` has no attribute `__getitem__`']"
  ],
  "typeddicts_inheritance.py": [
    "Line 65: Expected 1 errors",
    "Lines 54, 55: Expected error (tag 'Y1')",
    "Line 10: Unexpected errors ['untype, got object']",
    "Line 17: Unexpected errors ['untype, got object']",
    "Line 22: Unexpected errors ['EXPECTED dict[str, int | str] <: BookBasedMovie']",
    "Line 24: Unexpected errors ['EXPECTED BookBasedMovie <: BookBasedMovieAlso']",
    "Line 27: Unexpected errors ['untype, got object']",
    "Line 30: Unexpected errors ['untype, got object']",
    "Line 36: Unexpected errors [\"Unexpected keyword argument 'x'\", \"Unexpected keyword argument 'y'\", \"Unexpected keyword argument 'z'\"]",
    "Line 51: Unexpected errors ['untype, got object']",
    "Line 59: Unexpected errors ['untype, got object']",
    "Line 62: Unexpected errors ['untype, got object']"
  ],
  "typeddicts_operations.py": [
    "Line 11: Unexpected errors ['untype, got object']",
    "Line 18: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie']",
    "Line 19: Unexpected errors ['Object of class `Movie` has no attribute `__setitem__`']",
    "Line 20: Unexpected errors ['Object of class `Movie` has no attribute `__setitem__`']",
    "Line 41: Unexpected errors ['Object of class `Movie` has no attribute `get`']",
    "Line 53: Unexpected errors ['untype, got object']",
    "Line 58: Unexpected errors ['EXPECTED dict[@_, @_] <: MovieOptional']",
    "Line 60: Unexpected errors ['assert_type(Any, str | None) failed', 'Object of class `MovieOptional` has no attribute `get`']",
    "Line 64: Unexpected errors ['TODO: StmtDelete - Bindings::stmt']"
  ],
  "typeddicts_readonly.py": [
    "Line 36: Expected 1 errors",
    "Line 16: Unexpected errors ['untype, got object']",
    "Line 21: Unexpected errors ['EXPECTED dict[str, list[@_] | str] <: Band']",
    "Line 23: Unexpected errors ['Object of class `Band` has no attribute `__setitem__`']",
    "Line 25: Unexpected errors ['Object of class `Band` has no attribute `__getitem__`']",
    "Line 31: Unexpected errors ['Expected a callable, got object']",
    "Line 37: Unexpected errors ['Expected `dict.__getitem__` to be a callable, got Callable[[_PyreReadOnly_[dict[str, list[str] | str]], _PyreReadOnly_[str]], _PyreReadOnly_[list[str] | str]] | Callable[[dict[str, list[str] | str], str], list[str] | str]']",
    "Line 44: Unexpected errors ['untype, got object']",
    "Line 49: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie1']",
    "Line 54: Unexpected errors ['untype, got object']",
    "Line 56: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[ReadOnly[int]]`']",
    "Line 59: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie2']"
  ],
  "typeddicts_readonly_consistency.py": [
    "Line 19: Unexpected errors ['untype, got object']",
    "Line 23: Unexpected errors ['untype, got object']",
    "Line 28: Unexpected errors ['untype, got object']",
    "Line 34: Unexpected errors ['EXPECTED B1 <: A1']",
    "Line 35: Unexpected errors ['EXPECTED C1 <: A1']",
    "Line 41: Unexpected errors ['EXPECTED B1 <: C1']",
    "Line 65: Unexpected errors ['untype, got object']",
    "Line 69: Unexpected errors ['untype, got object']",
    "Line 73: Unexpected errors ['untype, got object']",
    "Line 78: Unexpected errors ['EXPECTED B2 <: A2']",
    "Line 79: Unexpected errors ['EXPECTED C2 <: A2']"
  ],
  "typeddicts_readonly_inheritance.py": [
    "Line 50: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 132: Expected 1 errors",
    "Line 14: Unexpected errors ['untype, got object']",
    "Line 23: Unexpected errors ['EXPECTED dict[str, int | str] <: Album1']",
    "Line 24: Unexpected errors ['Object of class `Album1` has no attribute `__setitem__`']",
    "Line 25: Unexpected errors ['Object of class `Album1` has no attribute `__setitem__`']",
    "Line 35: Unexpected errors ['EXPECTED dict[str, int | str] <: Album2']",
    "Line 42: Unexpected errors ['untype, got object']",
    "Line 57: Unexpected errors ['untype, got object']",
    "Line 71: Unexpected errors ['untype, got object']",
    "Line 80: Unexpected errors ['EXPECTED dict[str, str] <: User']",
    "Line 81: Unexpected errors ['Object of class `User` has no attribute `__setitem__`']",
    "Line 87: Unexpected errors ['untype, got object']",
    "Line 109: Unexpected errors ['untype, got object']",
    "Line 114: Unexpected errors ['untype, got object']",
    "Line 122: Unexpected errors ['untype, got object']",
    "Line 127: Unexpected errors ['untype, got object']"
  ],
  "typeddicts_readonly_kwargs.py": [
    "Line 18: Unexpected errors ['untype, got object']",
    "Line 23: Unexpected errors ['untype, got object']",
    "Line 36: Unexpected errors ['EXPECTED Callable[[KwArgs[Unpack[ReadOnlyArgs]]], None] <: Function']"
  ],
  "typeddicts_readonly_update.py": [
    "Line 16: Unexpected errors ['untype, got object']",
    "Line 21: Unexpected errors ['EXPECTED dict[str, int] <: A']",
    "Line 22: Unexpected errors ['EXPECTED dict[str, int] <: A']",
    "Line 28: Unexpected errors ['untype, got object']",
    "Line 34: Unexpected errors ['Object of class `A` has no attribute `update`']"
  ],
  "typeddicts_required.py": [
    "Line 12: Expected 1 errors",
    "Line 19: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 24: Unexpected errors ['untype, got object']",
    "Line 32: Unexpected errors ['untype, got object']",
    "Line 37: Unexpected errors ['untype, got object']",
    "Line 42: Unexpected errors ['untype, got object']",
    "Line 47: Unexpected errors ['EXPECTED dict[str, int] <: TD3']",
    "Line 48: Unexpected errors ['EXPECTED dict[str, int] <: TD4']",
    "Line 49: Unexpected errors ['EXPECTED dict[str, int] <: TD5']",
    "Line 53: Unexpected errors ['EXPECTED TD4 <: TD3']",
    "Line 54: Unexpected errors ['EXPECTED TD5 <: TD3']",
    "Line 55: Unexpected errors ['EXPECTED TD3 <: TD4']",
    "Line 56: Unexpected errors ['EXPECTED TD5 <: TD4']",
    "Line 57: Unexpected errors ['EXPECTED TD3 <: TD5']",
    "Line 58: Unexpected errors ['EXPECTED TD4 <: TD5']",
    "Line 61: Unexpected errors ['untype, got object']",
    "Line 66: Unexpected errors ['untype, got object']",
    "Line 68: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 70: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[Annotated[int, \"\"]]`']",
    "Line 73: Unexpected errors ['Expected a callable, got object']"
  ],
  "typeddicts_type_consistency.py": [
    "Line 10: Unexpected errors ['untype, got object']",
    "Line 14: Unexpected errors ['untype, got object']",
    "Line 18: Unexpected errors ['EXPECTED dict[str, int] <: B1']",
    "Line 24: Unexpected errors ['EXPECTED B1 <: Mapping[str, object]']",
    "Line 29: Unexpected errors ['untype, got object']",
    "Line 33: Unexpected errors ['untype, got object']",
    "Line 37: Unexpected errors ['EXPECTED dict[str, int] <: B2']",
    "Line 52: Unexpected errors ['untype, got object']",
    "Line 56: Unexpected errors ['untype, got object']",
    "Line 61: Unexpected errors ['EXPECTED dict[str, int] <: B3']",
    "Line 62: Unexpected errors ['EXPECTED B3 <: A3']",
    "Line 64: Unexpected errors ['EXPECTED dict[str, int] <: A3']",
    "Line 83: Unexpected errors ['EXPECTED B3 <: Mapping[str, object]']",
    "Line 84: Unexpected errors ['EXPECTED B3 <: Mapping[str, Any]']",
    "Line 88: Unexpected errors ['Expected a callable, got object']",
    "Line 91: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED _PyreReadOnly_[int | str | @_] | _PyreReadOnly_[int | str | None] | int | str | @_ | None <: str', \"EXPECTED Literal['name'] <: _PyreReadOnly_[dict[str, int | str]]\", \"EXPECTED Literal['name'] <: dict[str, int | str]\", \"EXPECTED Literal['n/a'] <: _PyreReadOnly_[str]\"]",
    "Line 92: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED _PyreReadOnly_[int | str | @_] | _PyreReadOnly_[int | str | None] | int | str | @_ | None <: int', \"EXPECTED Literal['age'] <: _PyreReadOnly_[dict[str, int | str]]\", \"EXPECTED Literal['age'] <: dict[str, int | str]\", 'EXPECTED Literal[42] <: _PyreReadOnly_[str]', 'EXPECTED Literal[42] <: str']",
    "Line 94: Unexpected errors ['Expected a callable, got object']",
    "Line 97: Unexpected errors ['Expected 1 more positional argument(s)', 'Expected 2 more positional argument(s)', 'EXPECTED _PyreReadOnly_[int | str | @_] | _PyreReadOnly_[int | str | None] | int | str | @_ | None <: str | None', \"EXPECTED Literal['name'] <: _PyreReadOnly_[dict[str, int | str]]\", \"EXPECTED Literal['name'] <: dict[str, int | str]\"]",
    "Line 103: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED _PyreReadOnly_[int | str | @_] | _PyreReadOnly_[int | str | None] | int | str | @_ | None <: int', \"EXPECTED Literal['age'] <: _PyreReadOnly_[dict[str, int | str]]\", \"EXPECTED Literal['age'] <: dict[str, int | str]\", 'EXPECTED Literal[42] <: _PyreReadOnly_[str]', 'EXPECTED Literal[42] <: str']",
    "Line 105: Unexpected errors ['Expected 1 more positional argument(s)', 'EXPECTED _PyreReadOnly_[int | str | @_] | _PyreReadOnly_[int | str | None] | int | str | @_ | None <: int | str', \"EXPECTED Literal['age'] <: _PyreReadOnly_[dict[str, int | str]]\", \"EXPECTED Literal['age'] <: dict[str, int | str]\", \"EXPECTED Literal['42'] <: _PyreReadOnly_[str]\"]",
    "Line 110: Unexpected errors ['untype, got object']",
    "Line 114: Unexpected errors ['untype, got object']",
    "Line 118: Unexpected errors ['untype, got object']",
    "Line 122: Unexpected errors ['EXPECTED dict[str, dict[str, dict[str, str]]] <: Outer1']",
    "Line 129: Unexpected errors ['untype, got object']",
    "Line 133: Unexpected errors ['untype, got object']",
    "Line 137: Unexpected errors ['untype, got object']",
    "Line 142: Unexpected errors ['untype, got object']",
    "Line 151: Unexpected errors ['EXPECTED dict[str, dict[str, int] | str] <: Outer2']",
    "Line 152: Unexpected errors ['EXPECTED Outer2 <: Outer3']"
  ],
  "typeddicts_usage.py": [
    "Line 35: Expected 1 errors",
    "Line 8: Unexpected errors ['untype, got object']",
    "Line 13: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie']",
    "Line 20: Unexpected errors ['EXPECTED dict[str, int | str] <: Movie']",
    "Line 30: Unexpected errors [\"Unexpected keyword argument 'name'\", \"Unexpected keyword argument 'year'\"]"
  ]
}