@generated
{
  "aliases_explicit.py": [
    "Line 85: Expected 1 errors",
    "Line 44: Unexpected errors ['Expected 1 type argument for `GoodTypeAlias12`, got 0']",
    "Line 98: Unexpected errors ['assert_type(list[Any], list[str]) failed']"
  ],
  "aliases_implicit.py": [
    "Line 81: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 112: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 58: Unexpected errors ['Expected 1 type argument for `GoodTypeAlias13`, got 0']"
  ],
  "aliases_newtype.py": [
    "Line 47: Expected 1 errors"
  ],
  "aliases_recursive.py": [
    "Line 19: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 14: Unexpected errors [\"Expected a type form, got instance of `Literal['Json']`\", \"Expected a type form, got instance of `Literal['Json']`\"]",
    "Line 24: Unexpected errors [\"Expected a type form, got instance of `Literal['Json2']`\", \"Expected a type form, got instance of `Literal['Json2']`\"]",
    "Line 30: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveTuple']`\"]",
    "Line 42: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveMapping']`\"]",
    "Line 58: Unexpected errors [\"`|` is not supported between `Literal['GenericTypeAlias1[T1]']` and `type[TypeVar[T1]]`\\n  TODO: Expr::binop_infer attribute base undefined for type: type[TypeVar[T1]] (trying to access __ror__)\"]",
    "Line 59: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 62: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 65: Unexpected errors [\"`|` is not supported between `Literal['GenericTypeAlias2[T1, T2]']` and `type[TypeVar[T1]]`\\n  TODO: Expr::binop_infer attribute base undefined for type: type[TypeVar[T1]] (trying to access __ror__)\"]",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]",
    "Line 68: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]"
  ],
  "aliases_type_statement.py": [
    "Line 26: Expected 1 errors",
    "Line 43: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors"
  ],
  "aliases_typealiastype.py": [
    "Line 44: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 17: Unexpected errors ['Argument `tuple[type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 18: Unexpected errors ['Argument `tuple[type[TypeVar[S]], type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 19: Unexpected errors ['Argument `tuple[type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 23: Unexpected errors ['Argument `tuple[type[TypeVar[S]], type[TypeVar[TStr]], type[ParamSpec[P]], type[TypeVarTuple[Ts]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 35: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 36: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 37: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 38: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 39: Unexpected errors ['Expected a type form, got instance of `GenericAlias`', 'Expected an iterable, got type[tuple[int, str, int]]']"
  ],
  "aliases_variance.py": [
    "Line 24: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "annotations_coroutines.py": [],
  "annotations_forward_refs.py": [
    "Line 22: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 87: Unexpected errors ['Expected a type form, got instance of `(self: ClassD) -> None`']",
    "Line 96: Unexpected errors ['assert_type(Any, int) failed']"
  ],
  "annotations_generators.py": [
    "Line 87: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 182: Unexpected errors ['assert_type(() -> AsyncIterator[int], () -> Coroutine[Any, Any, AsyncIterator[int]]) failed']",
    "Line 187: Unexpected errors ['Expected to yield a value of type `int`, but a bare `yield` gives `None` instead']"
  ],
  "annotations_methods.py": [
    "Line 19: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 23: Unexpected errors ['Expected a callable, got type[?_TypeVar]']"
  ],
  "annotations_typeexpr.py": [
    "Line 94: Expected 1 errors"
  ],
  "callables_annotation.py": [
    "Line 56: Expected 1 errors",
    "Line 155: Unexpected errors ['`Proto3` is not assignable to `Proto4[Ellipsis]`']",
    "Line 156: Unexpected errors ['`Proto4[Ellipsis]` is not assignable to `Proto3`']",
    "Line 157: Unexpected errors ['`Proto7` is not assignable to `Proto6`']"
  ],
  "callables_kwargs.py": [
    "Line 111: Expected 1 errors",
    "Line 122: Expected 1 errors"
  ],
  "callables_protocol.py": [],
  "callables_subtyping.py": [
    "Line 213: Unexpected errors ['`ProtocolWithP[?_ParamSpec]` is not assignable to `(ParamSpec(?_ParamSpec)) -> None`']",
    "Line 214: Unexpected errors ['`(ParamSpec(?_ParamSpec)) -> None` is not assignable to `ProtocolWithP[?_ParamSpec]`']"
  ],
  "classes_classvar.py": [
    "Line 54: Expected 1 errors"
  ],
  "classes_override.py": [
    "Lines 56, 65: Expected error (tag 'method4')"
  ],
  "constructors_call_init.py": [
    "Line 42: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 74: Unexpected errors ['assert_type(Class5[list[int]], Class5[set[str]]) failed', 'No matching overload found for function `Class5.__init__`, reporting errors for closest overload: `(value: int) -> None`', \"Argument `Literal['']` is not assignable to parameter `value` with type `int` in function `Class5.__init__`\"]",
    "Line 75: Unexpected errors ['assert_type(Class5[list[int]], Class5[float]) failed', 'No matching overload found for function `Class5.__init__`, reporting errors for closest overload: `(value: int) -> None`', 'Argument `float` is not assignable to parameter `value` with type `int` in function `Class5.__init__`']"
  ],
  "constructors_call_metaclass.py": [
    "Line 20: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class1`']",
    "Line 23: Unexpected errors ['assert_type(Class1, NoReturn) failed', 'Missing argument `x` in function `Class1.__new__`']",
    "Line 33: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class2`']",
    "Line 48: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class3`']",
    "Line 62: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class4`']"
  ],
  "constructors_call_new.py": [
    "Line 16: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class1[?_TypeVar]`']",
    "Line 29: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class2[?_TypeVar]`']",
    "Line 64: Unexpected errors ['assert_type(Class4, Class4 | Any) failed', 'Missing argument `x` in function `Class4.__init__`']",
    "Line 76: Unexpected errors ['assert_type(Class5, NoReturn) failed', 'Missing argument `x` in function `Class5.__init__`']",
    "Line 104: Unexpected errors ['assert_type(object, Class7) failed']"
  ],
  "constructors_call_type.py": [
    "Line 25: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class1`']",
    "Line 35: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class2`']",
    "Line 63: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 71: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 79: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 80: Unexpected errors ['Expected a callable, got type[?_TypeVar]']"
  ],
  "constructors_callable.py": [
    "Line 35: Unexpected errors ['Argument `type[Class1]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 37: Unexpected errors ['assert_type(Any, Class1) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 48: Unexpected errors ['Argument `type[Class2]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 50: Unexpected errors ['assert_type(Any, Class2) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 62: Unexpected errors ['Argument `type[Class3]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 64: Unexpected errors ['assert_type(Any, Class3) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 76: Unexpected errors ['Argument `type[Class4]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 78: Unexpected errors ['assert_type(Any, int) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 93: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class5`']",
    "Line 96: Unexpected errors ['Argument `type[Class5]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 100: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 105: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 124: Unexpected errors ['Argument `type[Class6]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 126: Unexpected errors ['assert_type(Any, Class6Proxy) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 141: Unexpected errors ['Argument `type[Class6Any]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 143: Unexpected errors ['Unexpected ParamSpec type: `Unknown`']",
    "Line 160: Unexpected errors ['Argument `type[Class7]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 164: Unexpected errors ['assert_type(Any, Class7[int]) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 165: Unexpected errors ['assert_type(Any, Class7[str]) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 178: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class8[?_TypeVar]`']",
    "Line 181: Unexpected errors ['Argument `type[Class8]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 183: Unexpected errors ['assert_type(Any, Class8[str]) failed', 'Unexpected ParamSpec type: `Unknown`']",
    "Line 192: Unexpected errors ['Argument `type[Class9]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 194: Unexpected errors ['assert_type(Any, Class9) failed', 'Unexpected ParamSpec type: `Unknown`']"
  ],
  "constructors_consistency.py": [
    "Line 22: Unexpected errors ['Returned type `object` is not assignable to declared return type `Class1`']"
  ],
  "dataclasses_descriptors.py": [
    "Line 35: Unexpected errors ['Argument `Literal[3]` is not assignable to parameter `y` with type `Desc1` in function `DC1.__init__`']"
  ],
  "dataclasses_final.py": [
    "Line 27: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors"
  ],
  "dataclasses_frozen.py": [
    "Lines 22, 23: Expected error (tag 'DC2')",
    "Lines 32, 33: Expected error (tag 'DC4')"
  ],
  "dataclasses_hash.py": [],
  "dataclasses_inheritance.py": [],
  "dataclasses_kwonly.py": [
    "Line 32: Unexpected errors ['Missing argument `a` in function `DC2.__init__`', 'Expected 0 positional arguments, got 1 in function `DC2.__init__`']",
    "Line 35: Unexpected errors ['Missing argument `a` in function `DC2.__init__`', 'Expected 0 positional arguments, got 1 in function `DC2.__init__`']",
    "Line 47: Unexpected errors ['Missing argument `a` in function `DC3.__init__`', 'Expected 0 positional arguments, got 1 in function `DC3.__init__`']",
    "Line 50: Unexpected errors ['Missing argument `a` in function `DC3.__init__`', 'Expected 0 positional arguments, got 1 in function `DC3.__init__`']",
    "Line 61: Unexpected errors ['Missing argument `c` in function `DC4.__init__`', 'Argument `float` is not assignable to parameter `b` with type `int` in function `DC4.__init__`', 'Multiple values for argument `b` in function `DC4.__init__`']"
  ],
  "dataclasses_order.py": [],
  "dataclasses_postinit.py": [
    "Line 19: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 29: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 23: Unexpected errors ['Argument `Literal[3]` is not assignable to parameter `x` with type `InitVar[int]` in function `DC1.__init__`', \"Argument `Literal['']` is not assignable to parameter `y` with type `InitVar[str]` in function `DC1.__init__`\"]"
  ],
  "dataclasses_slots.py": [
    "Line 25: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Lines 10, 11: Expected error (tag 'DC1')",
    "Line 56: Unexpected errors ['Class `DC5` has no class attribute `__slots__`']",
    "Line 57: Unexpected errors ['Object of class `DC5` has no attribute `__slots__`']"
  ],
  "dataclasses_transform_class.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 60: Unexpected errors ['Missing argument `not_a_field` in function `ModelBase.__init__`', 'Unexpected keyword argument `id` in function `ModelBase.__init__`', 'Unexpected keyword argument `name` in function `ModelBase.__init__`', 'Unexpected keyword argument `other_name` in function `ModelBase.__init__`']",
    "Line 68: Unexpected errors ['Missing argument `not_a_field` in function `ModelBase.__init__`', 'Unexpected keyword argument `id` in function `ModelBase.__init__`', 'Unexpected keyword argument `name` in function `ModelBase.__init__`']",
    "Line 74: Unexpected errors ['Missing argument `not_a_field` in function `ModelBase.__init__`', 'Unexpected keyword argument `id` in function `ModelBase.__init__`', 'Unexpected keyword argument `name` in function `ModelBase.__init__`']",
    "Line 76: Unexpected errors ['Missing argument `not_a_field` in function `ModelBase.__init__`', 'Unexpected keyword argument `id` in function `ModelBase.__init__`']",
    "Line 78: Unexpected errors ['`<` is not supported between `Customer2` and `Customer2`']",
    "Line 106: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`']",
    "Line 119: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']"
  ],
  "dataclasses_transform_converter.py": [
    "Line 118: Expected 1 errors",
    "Line 29: Unexpected errors ['Argument `tuple[Forall[S, T, (*, converter: (S) -> T, default: S | None, default_factory: (() -> S) | None) -> T]]` is not assignable to parameter `field_specifiers` with type `tuple[((...) -> Any) | type[Any], ...]` in function `typing.dataclass_transform`']",
    "Line 102: Unexpected errors ['Argument `type[ConverterClass]` is not assignable to parameter `converter` with type `(@_) -> @_` in function `model_field`']",
    "Line 104: Unexpected errors ['Argument `type[dict]` is not assignable to parameter `converter` with type `(@_) -> @_` in function `model_field`']",
    "Line 112: Unexpected errors ['Expected 0 positional arguments, got 5 in function `object.__init__`']",
    "Line 114: Unexpected errors [\"`Literal['f1']` is not assignable to attribute `field0` with type `int`\"]",
    "Line 115: Unexpected errors [\"`Literal['f6']` is not assignable to attribute `field3` with type `ConverterClass`\"]",
    "Line 116: Unexpected errors [\"`Literal[b'f6']` is not assignable to attribute `field3` with type `ConverterClass`\"]",
    "Line 121: Unexpected errors ['Expected 0 positional arguments, got 6 in function `object.__init__`']",
    "Line 132: Unexpected errors ['Argument `type[str]` is not assignable to parameter `default_factory` with type `(() -> str) | None` in function `model_field`']"
  ],
  "dataclasses_transform_field.py": [
    "Line 60: Unexpected errors ['Unexpected keyword argument `name` in function `object.__init__`']",
    "Line 77: Unexpected errors ['Unexpected keyword argument `name` in function `object.__init__`']"
  ],
  "dataclasses_transform_func.py": [
    "Line 97: Expected 1 errors",
    "Lines 89, 90: Expected error (tag 'Customer3Subclass')",
    "Line 50: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']",
    "Line 53: Unexpected errors ['Expected 0 positional arguments, got 2 in function `object.__init__`']",
    "Line 67: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']",
    "Line 73: Unexpected errors ['`<` is not supported between `Customer2` and `Customer2`']",
    "Line 94: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']"
  ],
  "dataclasses_transform_meta.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 60: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`', 'Unexpected keyword argument `other_name` in function `object.__init__`']",
    "Line 69: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']",
    "Line 75: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']",
    "Line 77: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`']",
    "Line 79: Unexpected errors ['`<` is not supported between `Customer2` and `Customer2`']",
    "Line 100: Unexpected errors ['Unexpected keyword argument `id` in function `object.__init__`', 'Unexpected keyword argument `name` in function `object.__init__`']"
  ],
  "dataclasses_usage.py": [
    "Lines 58, 61: Expected error (tag 'DC1')",
    "Lines 64, 67: Expected error (tag 'DC2')",
    "Lines 70, 73: Expected error (tag 'DC3')",
    "Line 72: Unexpected errors ['`Literal[0]` is not assignable to `InitVar[int]`']",
    "Line 205: Unexpected errors ['`DC15` is not assignable to `DataclassProto`']"
  ],
  "directives_assert_type.py": [],
  "directives_cast.py": [],
  "directives_deprecated.py": [
    "Line 18: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 69: Expected 1 errors",
    "Line 98: Expected 1 errors"
  ],
  "directives_no_type_check.py": [],
  "directives_reveal_type.py": [],
  "directives_type_checking.py": [],
  "directives_type_ignore.py": [],
  "directives_type_ignore_file1.py": [
    "Line 16: Unexpected errors [\"`Literal['']` is not assignable to `int`\"]"
  ],
  "directives_type_ignore_file2.py": [],
  "directives_version_platform.py": [],
  "enums_behaviors.py": [
    "Line 39: Expected 1 errors",
    "Line 19: Unexpected errors ['Type `type[Color]` is not iterable\\n  Argument `EnumMeta` is not assignable to parameter `self` with type `type[@_]` in function `enum.EnumMeta.__getitem__`', 'Type `type[Color]` is not iterable\\n  Argument `int` is not assignable to parameter `name` with type `str` in function `enum.EnumMeta.__getitem__`']",
    "Line 20: Unexpected errors ['assert_type(Any, Color) failed']",
    "Line 26: Unexpected errors ['assert_type(type[Color], Color) failed', 'Expected 0 type arguments for `Color`, got 1', \"Expected a type form, got instance of `Literal['RED']`\"]",
    "Line 27: Unexpected errors ['assert_type(Enum, Color) failed']"
  ],
  "enums_definition.py": [],
  "enums_expansion.py": [],
  "enums_member_names.py": [],
  "enums_member_values.py": [],
  "enums_members.py": [
    "Line 27: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet` is not visible on the class']",
    "Line 28: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet` is not visible on the class']",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet2` is not visible on the class']",
    "Line 36: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet2` is not visible on the class']",
    "Line 100: Unexpected errors ['assert_type(Literal[TrafficLight.AMBER], Literal[TrafficLight.YELLOW]) failed']",
    "Line 128: Unexpected errors ['Could not find name `reveal_type`']"
  ],
  "exceptions_context_managers.py": [
    "Line 50: Unexpected errors ['assert_type(str, int | str) failed']",
    "Line 57: Unexpected errors ['assert_type(str, int | str) failed']"
  ],
  "generics_base_class.py": [
    "Line 30: Expected 1 errors",
    "Line 68: Expected 1 errors"
  ],
  "generics_basic.py": [
    "Line 49: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Line 34: Unexpected errors ['`+` is not supported between `?_TypeVar` and `?_TypeVar`\\n  TODO: Expr::binop_infer attribute base undefined for type: ?_TypeVar (trying to access __add__)', '`+` is not supported between `?_TypeVar` and `?_TypeVar`\\n  TODO: Expr::binop_infer attribute base undefined for type: ?_TypeVar (trying to access __radd__)']",
    "Line 67: Unexpected errors ['assert_type(MyStr, str) failed']",
    "Line 68: Unexpected errors ['assert_type(MyStr, str) failed', 'Argument `str` is not assignable to parameter `y` with type `MyStr` in function `concat`']"
  ],
  "generics_defaults.py": [
    "Line 104: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 73: Unexpected errors ['Unexpected keyword argument `default` to ParamSpec']",
    "Line 79: Unexpected errors ['assert_type(type[Class_ParamSpec[Any]], type[Class_ParamSpec[(str, int)]]) failed']",
    "Line 80: Unexpected errors ['assert_type(Class_ParamSpec[(*Any, **Any)], Class_ParamSpec[(str, int)]) failed']",
    "Line 88: Unexpected errors ['Unexpected keyword argument `default` to TypeVarTuple']",
    "Line 94: Unexpected errors ['assert_type(type[Class_TypeVarTuple[Any]], type[Class_TypeVarTuple[tuple[str, int]]]) failed']",
    "Line 95: Unexpected errors ['assert_type(Class_TypeVarTuple[tuple[Any, ...]], Class_TypeVarTuple[tuple[str, int]]) failed']",
    "Line 127: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 145: Unexpected errors ['Unexpected keyword argument `default` to ParamSpec']",
    "Line 148: Unexpected errors ['Class `Foo6` uses type variables not specified in `Generic` or `Protocol` base']",
    "Line 151: Unexpected errors ['assert_type(type[Foo6[Ellipsis, tuple[str]]], type[Foo6[Ellipsis, tuple[str, (float, bool)]]]) failed', 'Expected a valid ParamSpec expression', 'Expected a valid ParamSpec expression']",
    "Line 152: Unexpected errors ['Expected a valid ParamSpec expression', 'Expected a valid ParamSpec expression']",
    "Line 166: Unexpected errors ['assert_type(Any, (Foo7[int]) -> Foo7[int]) failed', 'Generic attribute `meth` of class `Foo7` is not visible on the class']",
    "Line 167: Unexpected errors ['assert_type(Any, int) failed', 'Instance-only attribute `attr` of class `Foo7` is not visible on the class']"
  ],
  "generics_defaults_referential.py": [
    "Line 53: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 74: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 23: Unexpected errors ['assert_type(type[slice[int, TypeVar[StartT], int | None]], type[slice[int, int, int | None]]) failed']",
    "Line 24: Unexpected errors ['assert_type(slice[int, TypeVar[StartT], int | None], slice[int, int, int | None]) failed']",
    "Line 25: Unexpected errors ['assert_type(slice[str, TypeVar[StartT], int | None], slice[str, str, int | None]) failed']",
    "Line 94: Unexpected errors ['assert_type(type[Bar[Any, list[TypeVar[Z1]]]], type[Bar[Any, list[Any]]]) failed']",
    "Line 95: Unexpected errors ['assert_type(type[Bar[int, list[TypeVar[Z1]]]], type[Bar[int, list[int]]]) failed']",
    "Line 96: Unexpected errors ['assert_type(Bar[int, list[TypeVar[Z1]]], Bar[int, list[int]]) failed']"
  ],
  "generics_defaults_specialization.py": [],
  "generics_paramspec_basic.py": [
    "Line 15: Expected 1 errors"
  ],
  "generics_paramspec_components.py": [
    "Line 30: Expected 1 errors",
    "Line 96: Unexpected errors ['Argument `(a: int, b: str) -> int` is not assignable to parameter with type `(*Unknown, **Unknown) -> int` in function `twice`']",
    "Line 97: Unexpected errors ['Argument `(a: int, b: str) -> int` is not assignable to parameter with type `(*Unknown, **Unknown) -> int` in function `twice`']"
  ],
  "generics_paramspec_semantics.py": [],
  "generics_paramspec_specialization.py": [],
  "generics_scoping.py": [
    "Line 50: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "generics_self_advanced.py": [
    "Line 19: Unexpected errors ['assert_type(ParentA, ChildA) failed']",
    "Line 35: Unexpected errors ['assert_type(ChildB, Self) failed']",
    "Line 38: Unexpected errors ['assert_type(ParentB, Self) failed']",
    "Line 42: Unexpected errors ['assert_type(type[ChildB], type[Self]) failed']",
    "Line 43: Unexpected errors ['assert_type(Any, list[Self]) failed', 'Instance-only attribute `a` of class `ChildB` is not visible on the class']",
    "Line 44: Unexpected errors ['assert_type(Any, Self) failed', 'Instance-only attribute `a` of class `ChildB` is not visible on the class']",
    "Line 45: Unexpected errors ['assert_type(ParentB, Self) failed']"
  ],
  "generics_self_attributes.py": [
    "Line 29: Unexpected errors ['`OrdinalLinkedList` is not assignable to attribute `next` with type `Self | None`']"
  ],
  "generics_self_basic.py": [
    "Line 20: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 15: Unexpected errors ['Object of class `Shape` has no attribute `scale`']",
    "Line 27: Unexpected errors ['assert_type(type[Shape], type[Self]) failed']",
    "Line 40: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 52: Unexpected errors ['assert_type(Shape, Circle) failed']",
    "Line 55: Unexpected errors ['assert_type(Shape, Circle) failed']"
  ],
  "generics_self_protocols.py": [
    "Line 64: Expected 1 errors"
  ],
  "generics_self_usage.py": [
    "Line 73: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 101: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 50: Unexpected errors ['`(self: CallableAttribute) -> int` is not assignable to `(Self) -> int`']",
    "Line 60: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Self (trying to access x)']",
    "Line 63: Unexpected errors ['Argument `HasNestedFunction` is not assignable to parameter `inner_self` with type `Self` in function `nested`']",
    "Line 93: Unexpected errors ['Object of class `Foo3` has no attribute `child_value`']"
  ],
  "generics_syntax_compatibility.py": [],
  "generics_syntax_declarations.py": [
    "Line 46: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(type[?_TypeVar], TypeVar) failed']",
    "Line 15: Unexpected errors ['assert_type(type[?_TypeVarTuple], TypeVarTuple) failed']",
    "Line 16: Unexpected errors ['assert_type(type[?_ParamSpec], ParamSpec) failed']",
    "Line 33: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_TypeVar (trying to access capitalize)']"
  ],
  "generics_syntax_infer_variance.py": [
    "Line 28: Unexpected errors ['`ShouldBeCovariant1[int]` is not assignable to `ShouldBeCovariant1[float]`']",
    "Line 36: Unexpected errors ['`ShouldBeCovariant2[int]` is not assignable to `ShouldBeCovariant2[float]`']",
    "Line 45: Unexpected errors ['`ShouldBeCovariant3[int]` is not assignable to `ShouldBeCovariant3[float]`']",
    "Line 54: Unexpected errors ['`ShouldBeCovariant4[int]` is not assignable to `ShouldBeCovariant4[float]`']",
    "Line 67: Unexpected errors ['`ShouldBeCovariant5[int]` is not assignable to `ShouldBeCovariant5[float]`']",
    "Line 78: Unexpected errors ['`ShouldBeCovariant6[int]` is not assignable to `ShouldBeCovariant6[float]`']",
    "Line 149: Unexpected errors ['`ShouldBeContravariant1[float]` is not assignable to `ShouldBeContravariant1[int]`']"
  ],
  "generics_syntax_scoping.py": [
    "Line 14: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 66: Unexpected errors ['Found `S`, but it was not the global scope']",
    "Line 67: Unexpected errors ['assert_type(str, int) failed']",
    "Line 116: Unexpected errors ['assert_type(type[?_TypeVar], TypeVar) failed']"
  ],
  "generics_type_erasure.py": [],
  "generics_typevartuple_args.py": [],
  "generics_typevartuple_basic.py": [
    "Line 85: Unexpected errors ['Argument `tuple[float]` is not assignable to parameter `arg2` with type `tuple[int]` in function `func2`']"
  ],
  "generics_typevartuple_callable.py": [],
  "generics_typevartuple_concat.py": [
    "Line 56: Unexpected errors ['Returned type `tuple[*tuple[Unknown, ...], Unknown]` is not assignable to declared return type `tuple[*?_TypeVarTuple, ?_TypeVar]`']"
  ],
  "generics_typevartuple_overloads.py": [],
  "generics_typevartuple_specialization.py": [
    "Line 51: Unexpected errors ['assert_type(tuple[int, *tuple[Any, ...]], tuple[int]) failed']",
    "Line 59: Unexpected errors ['Class `Array2` uses type variables not specified in `Generic` or `Protocol` base']",
    "Line 67: Unexpected errors ['Expected 1 type argument for `Array1D`, got 0']",
    "Line 92: Unexpected errors ['Expected 2 type arguments for `VariadicTuple`, got 0']",
    "Line 94: Unexpected errors ['assert_type(tuple[float, *tuple[Any, ...]], tuple[float]) failed']",
    "Line 153: Unexpected errors ['Unpacked argument cannot be used for type parameter T1']",
    "Line 157: Unexpected errors ['assert_type(tuple[Any], tuple[*tuple[int, ...], int]) failed']"
  ],
  "generics_typevartuple_unpack.py": [],
  "generics_upper_bound.py": [
    "Line 24: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 31: Unexpected errors ['Argument `?_TypeVar` is not assignable to parameter with type `Sized` in function `len`', 'Argument `?_TypeVar` is not assignable to parameter with type `Sized` in function `len`']"
  ],
  "generics_variance.py": [
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 163: Expected 1 errors",
    "Line 167: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Lines 125, 126: Expected error (tag 'CoContra_Child2')",
    "Lines 131, 132: Expected error (tag 'CoContra_Child3')",
    "Lines 141, 142: Expected error (tag 'CoContra_Child5')",
    "Lines 195, 196: Expected error (tag 'ContraToContraToContra_WithTA')"
  ],
  "generics_variance_inference.py": [
    "Line 26: Unexpected errors ['`ClassA[float, int, int]` is not assignable to `ClassA[float, int, float]`']",
    "Line 29: Unexpected errors ['`ClassA[int, float, float]` is not assignable to `ClassA[int, int, float]`']",
    "Line 40: Unexpected errors ['`ShouldBeCovariant1[int]` is not assignable to `ShouldBeCovariant1[float]`']",
    "Line 48: Unexpected errors ['`ShouldBeCovariant2[int]` is not assignable to `ShouldBeCovariant2[float]`']",
    "Line 57: Unexpected errors ['`ShouldBeCovariant3[int]` is not assignable to `ShouldBeCovariant3[float]`']",
    "Line 66: Unexpected errors ['`ShouldBeCovariant4[int]` is not assignable to `ShouldBeCovariant4[float]`']",
    "Line 79: Unexpected errors ['`ShouldBeCovariant5[int]` is not assignable to `ShouldBeCovariant5[float]`']",
    "Line 150: Unexpected errors ['`ShouldBeContravariant1[float]` is not assignable to `ShouldBeContravariant1[int]`']",
    "Line 182: Unexpected errors ['`ShouldBeCovariant6[int]` is not assignable to `ShouldBeCovariant6[float]`']",
    "Line 193: Unexpected errors ['`ShouldBeContravariant2[float]` is not assignable to `ShouldBeContravariant2[int]`']"
  ],
  "historical_positional.py": [
    "Line 18: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 43: Expected 1 errors"
  ],
  "literals_interactions.py": [
    "Line 71: Unexpected errors ['`@` is not supported between `Matrix[Literal[2], Literal[3]]` and `Matrix[Literal[3], Literal[7]]`\\n  Argument `Matrix[Literal[3], Literal[7]]` is not assignable to parameter `other` with type `Matrix[Literal[3], int]` in function `Matrix.__matmul__`']",
    "Line 72: Unexpected errors ['assert_type(Matrix[Literal[2], int], Matrix[Literal[2], Literal[7]]) failed']",
    "Line 106: Unexpected errors [\"Argument `str` is not assignable to parameter `status` with type `Literal['ABORTED', 'MALFORMED']` in function `expects_bad_status`\"]"
  ],
  "literals_literalstring.py": [
    "Line 120: Expected 1 errors",
    "Line 52: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 111: Unexpected errors [\"assert_type(str, Literal['hello']) failed\"]"
  ],
  "literals_parameterizations.py": [
    "Line 46: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 33: Unexpected errors ['Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression']",
    "Line 35: Unexpected errors ['Invalid literal expression']"
  ],
  "literals_semantics.py": [],
  "namedtuples_define_class.py": [
    "Line 59: Expected 1 errors",
    "Line 79: Expected 1 errors"
  ],
  "namedtuples_define_functional.py": [],
  "namedtuples_type_compat.py": [],
  "namedtuples_usage.py": [],
  "narrowing_typeguard.py": [
    "Line 102: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 89: Unexpected errors ['assert_type(A, B) failed']",
    "Line 93: Unexpected errors ['assert_type(A, B) failed']"
  ],
  "narrowing_typeis.py": [
    "Line 105: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 199: Expected 1 errors",
    "Line 92: Unexpected errors ['assert_type(A, B) failed']",
    "Line 96: Unexpected errors ['assert_type(A, B) failed']"
  ],
  "overloads_basic.py": [],
  "protocols_class_objects.py": [
    "Line 29: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 104: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors"
  ],
  "protocols_definition.py": [
    "Line 116: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 281: Unexpected errors ['`Concrete5_Good2` is not assignable to `Template5`']"
  ],
  "protocols_explicit.py": [
    "Line 27: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 165: Expected 1 errors",
    "Line 157: Unexpected errors ['Class member `Mixin7.method1` overrides parent class `Proto7` in an inconsistent manner']"
  ],
  "protocols_generic.py": [
    "Line 87: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_TypeVar (trying to access get_parent)']",
    "Line 144: Unexpected errors ['`ConcreteHasProperty1` is not assignable to `HasPropertyProto`']",
    "Line 145: Unexpected errors ['`ConcreteHasProperty2` is not assignable to `HasPropertyProto`']"
  ],
  "protocols_merging.py": [
    "Line 82: Expected 1 errors"
  ],
  "protocols_modules.py": [
    "Line 25: Unexpected errors ['`Module[_protocols_modules1]` is not assignable to `Options1`']"
  ],
  "protocols_recursive.py": [
    "Line 80: Unexpected errors ['Argument `ImplB` is not assignable to parameter `x` with type `ProtoA[Never, @_]` in function `func1`']",
    "Line 81: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "protocols_runtime_checkable.py": [
    "Line 23: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 88: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "protocols_self.py": [
    "Line 32: Unexpected errors ['`One` is not assignable to variable `c` with type `Copyable`']",
    "Line 33: Unexpected errors ['`Other` is not assignable to variable `c` with type `Copyable`']",
    "Line 72: Unexpected errors ['`C2[str]` is not assignable to `P2Parent[str]`']",
    "Line 73: Unexpected errors ['`C2[str]` is not assignable to `P2Child[str]`']"
  ],
  "protocols_subtyping.py": [
    "Line 16: Expected 1 errors"
  ],
  "protocols_variance.py": [
    "Line 21: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 104: Expected 1 errors"
  ],
  "qualifiers_annotated.py": [
    "Line 48: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 81: Unexpected errors ['Expected a callable, got type[?_TypeVar]']"
  ],
  "qualifiers_final_annotation.py": [
    "Line 16: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors",
    "Line 149: Expected 1 errors",
    "Line 152: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 131: Unexpected errors ['Expected first item to be a string literal', 'Expected first item to be a string literal']",
    "Line 133: Unexpected errors ['Unexpected keyword argument `x` in function `N.__new__`', 'Unexpected keyword argument `y` in function `N.__new__`']"
  ],
  "qualifiers_final_decorator.py": [
    "Lines 67, 75: Expected error (tag 'method4')",
    "Lines 80, 89: Expected error (tag 'Derived3')",
    "Lines 84, 85, 86: Expected error (tag 'Derived3-2')",
    "Lines 94, 102: Expected error (tag 'Derived4')",
    "Lines 125, 126: Expected error (tag 'func')",
    "Line 81: Unexpected errors ['`method` is declared as final in parent class `Base3`']",
    "Line 95: Unexpected errors ['`method` is declared as final in parent class `Base4`']"
  ],
  "specialtypes_any.py": [],
  "specialtypes_never.py": [
    "Line 32: Unexpected errors [\"Returned type `Literal['whatever works']` is not assignable to declared return type `int`\"]"
  ],
  "specialtypes_none.py": [
    "Line 39: Unexpected errors ['Argument `type[object]` is not assignable to parameter `val1` with type `type[None]` in function `func2`']",
    "Line 40: Unexpected errors ['Argument `type` is not assignable to parameter `val1` with type `type[None]` in function `func2`']"
  ],
  "specialtypes_promotions.py": [],
  "specialtypes_type.py": [
    "Line 70: Expected 1 errors",
    "Line 39: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 84: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 99: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 100: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 102: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 106: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed', 'TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access __mro__)']",
    "Line 107: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 108: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 110: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 137: Unexpected errors ['assert_type(Type, type[Any]) failed']",
    "Line 139: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 152: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA7, type[type[TypeVar[T]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA8, type[type[TypeVar[T]]]]\"]",
    "Line 160: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 161: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 165: Unexpected errors ['`type` is not assignable to `(...) -> Any`']",
    "Line 166: Unexpected errors ['`type` is not assignable to `(int, int) -> int`']",
    "Line 169: Unexpected errors ['`type` is not assignable to `type[int]`']",
    "Line 170: Unexpected errors ['`type` is not assignable to `type[Any]`']",
    "Line 175: Unexpected errors ['Returned type `type` is not assignable to declared return type `type[?_TypeVar]`']"
  ],
  "tuples_type_compat.py": [
    "Line 74: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int]) failed']",
    "Line 78: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, int] | tuple[str, str]) failed']",
    "Line 82: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, str, int]) failed']",
    "Line 93: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 2) into 1 value']",
    "Line 95: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int]) failed']",
    "Line 97: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 1) into 2 values']",
    "Line 99: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, int] | tuple[str, str]) failed']",
    "Line 101: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 1) into 3 values', 'Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 2) into 3 values']",
    "Line 103: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, str, int]) failed']",
    "Line 115: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, str]) failed']",
    "Line 117: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, int]) failed']"
  ],
  "tuples_type_form.py": [],
  "tuples_unpacked.py": [],
  "typeddicts_alt_syntax.py": [],
  "typeddicts_class_syntax.py": [
    "Line 33: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 34: Unexpected errors ['TypedDict item `method2` may not be initialized']",
    "Line 39: Unexpected errors ['TypedDict item `method3` may not be initialized']"
  ],
  "typeddicts_final.py": [],
  "typeddicts_inheritance.py": [
    "Line 65: Expected 1 errors"
  ],
  "typeddicts_operations.py": [
    "Line 60: Unexpected errors ['assert_type(object | None, str | None) failed']"
  ],
  "typeddicts_readonly.py": [],
  "typeddicts_readonly_consistency.py": [
    "Line 38: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 79: Unexpected errors ['`TypedDict[C2]` is not assignable to `TypedDict[A2]`']"
  ],
  "typeddicts_readonly_inheritance.py": [
    "Line 94: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 132: Expected 1 errors",
    "Line 49: Unexpected errors ['Class member `RecordShop.albums` overrides parent class `AlbumCollection` in an inconsistent manner']",
    "Line 76: Unexpected errors ['Class member `User.ident` overrides parent class `OptionalIdent` in an inconsistent manner']"
  ],
  "typeddicts_readonly_kwargs.py": [],
  "typeddicts_readonly_update.py": [
    "Line 34: Unexpected errors ['Object of class `Mapping` has no attribute `update`']"
  ],
  "typeddicts_required.py": [
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 74: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveMovie']`\"]"
  ],
  "typeddicts_type_consistency.py": [
    "Line 21: Expected 1 errors",
    "Line 91: Unexpected errors ['`object | @_` is not assignable to `str`']",
    "Line 92: Unexpected errors ['`object | @_` is not assignable to `int`']",
    "Line 97: Unexpected errors ['`object | None` is not assignable to `str | None`']",
    "Line 103: Unexpected errors ['`object | @_` is not assignable to `int`']",
    "Line 105: Unexpected errors ['`object | @_` is not assignable to `int | str`']",
    "Line 151: Unexpected errors [\"`dict[str, int]` is not assignable to TypedDict key `z` with type `Literal[''] | TypedDict[Inner3]`\"]"
  ],
  "typeddicts_usage.py": [
    "Line 35: Expected 1 errors",
    "Line 40: Expected 1 errors"
  ]
}